CREATE ROLE exw_store LOGIN PASSWORD 'exw_store_local_only' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE exw_store OWNER exw_store;
REVOKE CONNECT ON DATABASE exw FROM PUBLIC;
GRANT CONNECT ON DATABASE exw TO exw;
