import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import rateLimit from '@fastify/rate-limit';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import {randomUUID} from 'node:crypto';
import {pool,transaction,type Context,type Tx,type Table,type Row,tables} from '../../../packages/database/src/index.ts';
import {config} from '../../../packages/database/src/config.ts';
import {balances,reconciliation,journal,debit,credit} from '../../../packages/database/src/ledger.ts';
import {DomainError,ensure,amount,money,csv,scopes,capabilities} from '../../../packages/domain/src/index.ts';
import {bodySchema as B,moneySchema as M,stringSchema as S,orderSchema,errorSchema} from '../../../packages/contracts/src/index.ts';
import {sessionContext,tokenContext,hash,passwordHash,passwordCheck,randomToken,newSession,sanitize,merchantOwn,userOwn,encrypt,decrypt,webhookAddress} from './security.ts';
import {createWorkspace,populate} from './seed.ts';
import {idempotent,createOrder,createCheckout,orderSummary,approve,capture,voidAuthorization,refund,topup,transfer,payout} from './payments.ts';
import {credentialCreate,endpointCreate,paymentRequest,payRequest,plan,subscription,consent,subscriptionAction,openDispute,disputeMessage} from './services.ts';
import {registerExtensions} from './extensions.ts';
import {curlExamples} from './playground.ts';
import {responseSchema,listQuerySchema} from '../../../packages/contracts/src/responses.ts';
type Auth='public'|'session'|'consumer'|'merchant'|'admin';
type Request = any;
const moneyBody=B({amount:M},['amount']);
const empty=B({});
/** Stored replay responses never repeat one-time secrets. */
const withoutSecrets=(r:any)=>r&&typeof r==='object'&&!Array.isArray(r)?Object.fromEntries(Object.entries(r).filter(([k])=>!['client_secret','webhook_secret'].includes(k))):r;
const cookieOptions={httpOnly:true,secure:!config.local||config.cookieSameSite==='none',sameSite:config.cookieSameSite,path:'/',maxAge:86400};
// Fixed demo sign-in (DEMO_LOGIN_ID / DEMO_LOGIN_PASSWORD) for the sample consumer account. Hashed once so that
// a wrong password costs the same work as a right one, and so the value is never compared byte by byte.
const demoLoginHash=config.demoLoginPassword?passwordHash(config.demoLoginPassword):'';
function builtInDemoLogin(identifier:string,password:string){return !!demoLoginHash&&identifier===config.demoLoginId&&passwordCheck(password,demoLoginHash);}
function sendSession(reply:any,s:any){reply.setCookie('exw_session',s.token,cookieOptions);if(s.owner_token)reply.setCookie('exw_demo',s.owner_token,{...cookieOptions,maxAge:7*86400});const {token,owner_token,...safe}=s;return safe;}
async function paged(tx:Tx,table:Table,q:any,scope:'merchant'|'user'|'all'='merchant'){
 let extra='',values:unknown[]=[];const add=(sql:string,v:unknown)=>{values.push(v);extra+=' AND '+sql.replace('?',`$${values.length+2}`);};
 if(scope==='merchant')add('merchant_id=?',tx.ctx.merchant);if(scope==='user')add('user_id=?',tx.ctx.user);
 if(q.status)add('status=?',q.status);if(q.q)add("(coalesce(business_key,'')||id||data::text) ILIKE ?",'%'+String(q.q).slice(0,100)+'%');
 if(q.from){ensure(!isNaN(Date.parse(q.from)));add('created_at>=?::timestamptz',q.from);}if(q.to){ensure(!isNaN(Date.parse(q.to)));add('created_at<=?::timestamptz',q.to);}
 if(q.cursor){let c;try{c=JSON.parse(Buffer.from(q.cursor,'base64url').toString());}catch{throw new DomainError('INVALID_REQUEST');}ensure(c&&typeof c.id==='string'&&!isNaN(Date.parse(c.at)));values.push(c.at,c.id);extra+=` AND (created_at,id)<($${values.length+1}::timestamptz,$${values.length+2})`;}
 const limit=Math.min(100,Math.max(1,Math.trunc(Number(q.limit)||25)));const rows=await tx.rows(table,extra+` ORDER BY created_at DESC,id DESC LIMIT ${limit+1}`,values);const last=rows[limit-1];return {data:rows.slice(0,limit).map(sanitize),next_cursor:rows.length>limit?Buffer.from(JSON.stringify({at:last.created_at,id:last.id})).toString('base64url'):null};
}
export async function buildApp() {
 const app=Fastify({logger:false,bodyLimit:65536,genReqId:()=>`req_${randomUUID()}`,trustProxy:false});
 await app.register(cookie);await app.register(cors,{origin:[config.portalUrl,config.storeUrl],credentials:true,exposedHeaders:['x-request-id']});
 await app.register(rateLimit,{max:3000,timeWindow:'1 minute',errorResponseBuilder:(_r,context)=>({statusCode:429,code:'RATE_LIMITED',message:'しばらく待って再試行してください。'})});
 const authenticatedLimit=app.createRateLimit({max:300,timeWindow:'1 minute',keyGenerator:(req:any)=>req.ctx.workspace+':'+req.ctx.generation+':'+req.ctx.actor});
 async function limitActor(req:any,reply:any){const limit=await authenticatedLimit(req);if(!limit.isAllowed&&limit.isExceeded){reply.header('Retry-After',Math.max(1,Math.ceil(limit.ttl/1000)));throw new DomainError('RATE_LIMITED','しばらく待って再試行してください。',429);}}
 await app.register(swagger,{openapi:{info:{title:'ExPress API',version:'1.0.0',description:'隔離デモ。実資金は動きません。金額はJPY整数文字列。金銭POSTにはIdempotency-Keyが必要です。'},servers:[{url:config.apiUrl}],components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer'},sessionCookie:{type:'apiKey',in:'cookie',name:'exw_session'}}}}});
 await app.register(swaggerUi,{routePrefix:'/docs',uiConfig:{docExpansion:'list'}});
 app.addHook('onRequest',async(req,reply)=>{reply.header('x-request-id',req.id).header('Cache-Control','no-store').header('X-Content-Type-Options','nosniff').header('Referrer-Policy','no-referrer');(req as any).start=Date.now();});
 app.addHook('onResponse',async(req,reply)=>{const ctx=(req as any).ctx as Context|undefined;if(!ctx)return;try{await transaction(ctx,tx=>tx.create('api_logs',{merchant_id:ctx.merchant,user_id:ctx.user,data:{request_id:req.id,path:req.url.split('?')[0],method:req.method,status:reply.statusCode,latency_ms:Date.now()-(req as any).start}}));}catch{}});
 app.setErrorHandler((e:any,req,reply)=>{const status=e.validation?400:e instanceof DomainError?e.status:e.statusCode??500;(req as any).resultStatus=status;reply.code(status).send({error:{code:e.validation?'INVALID_REQUEST':e instanceof DomainError?e.code:status===429?'RATE_LIMITED':'INTERNAL_ERROR',message:e.validation?'入力形式を確認してください。':e instanceof DomainError?e.message:'処理を完了できませんでした。request IDで確認してください。',request_id:req.id,details:[]}});});
 function route(method:string,url:string,auth:Auth,summary:string,handler:(req:Request,reply:any,tx:Tx)=>Promise<any>,options:{scope?:string;body?:any;financial?:boolean;idempotent?:boolean;roles?:string[]}={}){
  const headers:any={type:'object',properties:{'idempotency-key':{type:'string',minLength:8,maxLength:200},'x-csrf-token':{type:'string'}}};if(options.financial)headers.required=['idempotency-key'];
  app.route({method:method as any,url,schema:{summary,description:(options.scope?'Required scope: '+options.scope+'. ':'')+(options.roles?'Allowed roles: '+options.roles.join(', ')+'. ':'')+(options.financial?'Idempotency-Key required. A pending response is 202; poll operation_id. ':options.idempotent?'Idempotency-Key optional: the same key with the same input replays the stored result; one-time secrets are not repeated. ':'')+(auth!=='public'?'Session mutations require exact Origin and X-CSRF-Token.':''),...(method==='GET'&&!url.includes(':')&&url!=='/v1/openapi.json'?{querystring:listQuerySchema}:{}),...(url.includes(':')?{params:{type:'object',required:[...url.matchAll(/:([a-z_]+)/g)].map(m=>m[1]),properties:Object.fromEntries([...url.matchAll(/:([a-z_]+)/g)].map(m=>[m[1],{type:'string',minLength:1,maxLength:128}]))}}:{}),tags:[auth],security:auth==='public'?[]:auth==='merchant'?[{bearerAuth:[]},{sessionCookie:[]}]:[{sessionCookie:[]}],headers,...(options.body?{body:options.body}:{}),response:{...(url==='/v1/openapi.json'||url.includes('transactions')||url.endsWith('/reports')?{}:{200:responseSchema(method,url),...(options.financial?{202:{...responseSchema(method,url),description:'処理中。operation_idを照会する。'}}:{})}),400:errorSchema,401:errorSchema,403:errorSchema,404:errorSchema,409:errorSchema,429:errorSchema}},config:{rateLimit:url.includes('/auth/')||url==='/v1/demo/start'?{max:20,timeWindow:60000}:undefined},handler:async(req:any,reply)=>{
   if(auth==='public')return handler(req,reply,undefined as any);
   let ctx:Context;
   if(req.headers.authorization){ensure(auth==='merchant','FORBIDDEN',undefined,403);ctx=await tokenContext(req.headers.authorization.replace(/^Bearer /,''),req.id);}
   else {const session=await sessionContext(req.cookies.exw_session??'',req.id);ctx=session.ctx;if(method!=='GET')ensure(req.headers.origin===config.portalUrl&&req.headers['x-csrf-token']===session.csrf,'FORBIDDEN','CSRF検証に失敗しました。',403);}
   if(auth==='consumer')ensure(ctx.role==='consumer','FORBIDDEN',undefined,403);if(auth==='admin')ensure(ctx.role==='admin','FORBIDDEN',undefined,403);
   if(auth==='merchant')ensure(ctx.merchant,'FORBIDDEN',undefined,403);if(options.scope)ensure(ctx.scopes.includes(options.scope),'FORBIDDEN','必要なスコープがありません。',403);if(options.roles)ensure(options.roles.includes(ctx.role),'FORBIDDEN',undefined,403);
   req.ctx=ctx;await limitActor(req,reply);
   const key=req.headers['idempotency-key'];const replayable=options.financial||(options.idempotent===true&&typeof key==='string');
   const result=await transaction(ctx,tx=>replayable?idempotent(tx,method+' '+url,req.params.id??'',key,req.body,()=>handler(req,reply,tx),options.financial?undefined:withoutSecrets):handler(req,reply,tx));
   if(options.financial&&['pending','requested'].includes(result?.status)){reply.code(202);return {...result,operation_id:result.id};}return result;
  }});
 }
 route('GET','/v1/health','public','稼働確認',async()=>{await pool.query('SELECT 1');return {name:'ExPress',status:'ok',demo:true};});
 route('GET','/v1/openapi.json','public','OpenAPI',async()=>app.swagger());
 route('POST','/v1/demo/start','public','隔離デモを開始',async(req,reply)=>{ensure(req.headers.origin===config.portalUrl,'FORBIDDEN',undefined,403);if(config.singleWorkspace&&config.local){const existing=(await pool.query("SELECT s.* FROM sessions s JOIN demo_workspaces w ON w.id=s.workspace_id AND w.generation=s.generation WHERE role='consumer' AND NOT revoked AND w.status='active' ORDER BY s.created_at LIMIT 1")).rows[0];if(existing)return transaction({workspace:existing.workspace_id,generation:existing.generation,actor:'system',role:'system',scopes:[],requestId:req.id},async tx=>{const ownerToken=randomToken();await tx.db.query('INSERT INTO demo_access VALUES($1,$2,$3)',[hash(ownerToken),tx.ctx.workspace,new Date(Date.now()+7*86400000)]);return sendSession(reply,{...await newSession(tx,await tx.get('users',existing.user_id)),owner_token:ownerToken});});}return sendSession(reply,await createWorkspace());},{body:empty});
 route('GET','/v1/session','session','現在のセッション',async(req,_reply,tx)=>{const s=(await tx.db.query('SELECT csrf FROM sessions WHERE id=$1',[tx.ctx.session])).rows[0];return {user:sanitize(await tx.get('users',tx.ctx.user!)),role:tx.ctx.role,merchant_id:tx.ctx.merchant,csrf:s.csrf,workspace_id:tx.ctx.workspace,generation:tx.ctx.generation,now:tx.now(),presets:(await tx.rows('users')).filter(u=>u.data.preset).map(u=>({id:u.id,name:u.data.name,preset:u.data.preset}))};});
 route('POST','/v1/demo/switch','session','デモ人物へ切替',async(req,reply,tx)=>{const u=(await tx.rows('users','AND data->>\'preset\'=$3',[req.body.preset]))[0];ensure(u,'RESOURCE_NOT_FOUND',undefined,404);await tx.db.query('UPDATE sessions SET revoked=true WHERE id=$1',[tx.ctx.session]);return sendSession(reply,await newSession(tx,u));},{body:B({preset:S},['preset'])});
 route('POST','/v1/demo/reset','session','現在のデモだけを再生成',async(req,reply,tx)=>{ensure(req.body.confirm==='RESET');await tx.db.query('UPDATE jobs SET status=\'cancelled\' WHERE workspace_id=$1 AND generation=$2 AND status IN (\'pending\',\'running\')',[tx.ctx.workspace,tx.ctx.generation]);await tx.db.query('UPDATE sessions SET revoked=true WHERE workspace_id=$1',[tx.ctx.workspace]);await tx.db.query('UPDATE demo_workspaces SET generation=generation+1,clock_offset=0 WHERE id=$1',[tx.ctx.workspace]);tx.ctx.generation++;tx.workspace.generation++;tx.workspace.clock_offset='0';await tx.db.query('INSERT INTO workspace_generations VALUES($1,$2)',[tx.ctx.workspace,tx.ctx.generation]);const seed=await populate(tx);return sendSession(reply,{...await newSession(tx,seed.user),store_handoff:seed.store_handoff});},{body:B({confirm:S},['confirm'])});
 route('POST','/v1/auth/register','session','デモ利用者を登録',async(req,reply,tx)=>{ensure(tx.ctx.role==='consumer','FORBIDDEN',undefined,403);ensure(req.body.password.length>=12&&req.body.password.length<=200);ensure(!(await tx.rows('users',"AND lower(data->>'email')=$3",[req.body.email.toLowerCase()])).length,'INVALID_REQUEST','この登録情報は利用できません。');const u=await tx.create('users',{data:{name:req.body.name,email:req.body.email.toLowerCase(),password_hash:passwordHash(req.body.password),language:'ja',timezone:'Asia/Tokyo',kyc:'unsubmitted',capabilities:Object.fromEntries(capabilities.map(c=>[c,true]))}});await tx.create('wallets',{user_id:u.id});return sendSession(reply,await newSession(tx,u));},{body:B({name:S,email:{type:'string',format:'email'},password:S},['name','email','password'])});
 route('POST','/v1/auth/login','public','パスワードでログイン',async(req,reply)=>{ensure(req.headers.origin===config.portalUrl,'FORBIDDEN',undefined,403);const identifier=String(req.body.email).trim().toLowerCase();const w=(await pool.query('SELECT w.* FROM demo_access d JOIN demo_workspaces w ON w.id=d.workspace_id WHERE d.id=$1 AND d.expires_at>now()',[hash(req.cookies.exw_demo??'')])).rows[0];
  // No workspace yet (first visit, cleared cookies, or expired access): the built-in demo account creates its own
  // isolated workspace so that the sign-in form works on its own. Any other credential still needs a workspace first.
  if(!w){ensure(builtInDemoLogin(identifier,req.body.password),'UNAUTHENTICATED','デモ環境を作成してからログインしてください。',401);return sendSession(reply,await createWorkspace());}
  return transaction({workspace:w.id,generation:w.generation,actor:'login',role:'system',scopes:[],requestId:req.id},async tx=>{const u=(await tx.rows('users',"AND (lower(data->>'email')=$3 OR lower(data->>'login_id')=$3)",[identifier]))[0];ensure(u&&passwordCheck(req.body.password,u.data.password_hash),'UNAUTHENTICATED','ログイン情報を確認してください。',401);return sendSession(reply,await newSession(tx,u));});},{body:B({email:S,password:S},['email','password'])});
 route('POST','/v1/auth/logout','session','ログアウト',async(req,reply,tx)=>{await tx.db.query('UPDATE sessions SET revoked=true WHERE id=$1',[tx.ctx.session]);reply.clearCookie('exw_session',{path:'/'});return {status:'logged_out'};},{body:empty});
 route('POST','/v1/me/sessions/revoke-others','session','他の端末をログアウト',async(_r,_p,tx)=>{await tx.db.query('UPDATE sessions SET revoked=true WHERE workspace_id=$1 AND generation=$2 AND user_id=$3 AND id<>$4',[tx.ctx.workspace,tx.ctx.generation,tx.ctx.user,tx.ctx.session]);return {status:'revoked'};},{body:empty});
 route('PATCH','/v1/me/profile','consumer','プロフィール設定',async(req,_p,tx)=>{const u=await tx.get('users',tx.ctx.user!);try{new Intl.DateTimeFormat('ja',{timeZone:req.body.timezone});}catch{throw new DomainError('INVALID_REQUEST');}return sanitize(await tx.update('users',u.id,{data:{...u.data,name:req.body.name,language:req.body.language,timezone:req.body.timezone}}));},{body:B({name:S,language:{enum:['ja','en']},timezone:S},['name','language','timezone'])});
 route('POST','/v1/me/verification','consumer','模擬本人確認を提出',async(_r,_p,tx)=>{const u=await tx.get('users',tx.ctx.user!);return sanitize(await tx.update('users',u.id,{data:{...u.data,kyc:'pending'}}));},{body:empty});
 route('GET','/v1/me/overview','consumer','ウォレット概要',async(_r,_p,tx)=>({user:sanitize(await tx.get('users',tx.ctx.user!)),balances:await balances(tx,tx.ctx.user!),methods:(await tx.rows('payment_methods','AND user_id=$3',[tx.ctx.user])).map(sanitize),recipients:(await tx.rows('users')).filter(u=>u.id!==tx.ctx.user&&!u.data.admin&&!u.data.preset?.startsWith('merchant')).map(u=>({id:u.id,name:u.data.name})),notifications:await tx.rows('notifications','AND user_id=$3 ORDER BY created_at DESC',[tx.ctx.user]),subscriptions:await tx.rows('subscriptions',"AND (user_id=$3 OR status='pending_consent')",[tx.ctx.user]),requests:await tx.rows('payment_requests'),disputes:await tx.rows('disputes','AND user_id=$3',[tx.ctx.user])}));
 route('GET','/v1/me/balances','consumer','ウォレット残高',async(_r,_p,tx)=>balances(tx,tx.ctx.user!));
 route('GET','/v1/me/transactions','consumer','利用者の明細',async(req,reply,tx)=>history(req,reply,tx,tx.ctx.user!));
 route('POST','/v1/me/topups','consumer','模擬チャージ',async(req,_p,tx)=>topup(tx,req.body),{body:moneyBody,financial:true});
 route('POST','/v1/me/transfers','consumer','利用者間送金',async(req,_p,tx)=>transfer(tx,req.body),{body:B({amount:M,recipient_id:S,memo:S},['amount','recipient_id']),financial:true});
 route('POST','/v1/me/payouts','consumer','模擬銀行出金',async(req,_p,tx)=>payout(tx,req.body),{body:B({amount:M,payment_method_id:S},['amount','payment_method_id']),financial:true});
 for(const table of ['topups','payouts','transfers','notifications'] as const)route('GET',`/v1/me/${table}`,'consumer',`利用者 ${table} 一覧`,async(req,_p,tx)=>paged(tx,table,req.query,'user'));
 route('POST','/v1/me/notifications/:id/read','consumer','通知を既読にする',async(req,_p,tx)=>{const r=await tx.get('notifications',req.params.id);userOwn(tx,r);return tx.update('notifications',r.id,{status:'read'});},{body:empty});
 route('POST','/v1/me/payment-methods','consumer','模擬支払手段を登録',async(req,_p,tx)=>tx.create('payment_methods',{user_id:tx.ctx.user,data:{type:req.body.type,label:req.body.type==='bank'?'デモ銀行':req.body.card==='decline'?'デモ拒否カード':'デモ Visa',brand:req.body.type==='card'?'Visa':undefined,last4:req.body.card==='decline'?'0002':'4242',expires:'2030-12',provider_token:'mock_'+(req.body.card==='decline'?'decline_':'')+randomUUID(),default:false}}),{body:B({type:{enum:['card','bank']},card:{enum:['success','decline']}},['type'])});
 route('DELETE','/v1/me/payment-methods/:id','consumer','支払手段の新規利用を停止',async(req,_p,tx)=>{const m=await tx.get('payment_methods',req.params.id);userOwn(tx,m);return tx.update('payment_methods',m.id,{status:'deleted',data:{...m.data,default:false}});});
 route('POST','/v1/me/payment-methods/:id/default','consumer','既定の支払手段',async(req,_p,tx)=>{const m=await tx.get('payment_methods',req.params.id);userOwn(tx,m);ensure(m.status==='active');for(const x of await tx.rows('payment_methods','AND user_id=$3',[tx.ctx.user]))await tx.update('payment_methods',x.id,{data:{...x.data,default:x.id===m.id}});return tx.get('payment_methods',m.id);},{body:empty});
 route('POST','/v1/me/payment-requests','consumer','支払依頼リンクを作成',async(req,_p,tx)=>paymentRequest(tx,req.body),{body:B({amount:M,memo:S},['amount']),financial:true});
 route('POST','/v1/me/payment-requests/:id/approve','consumer','支払依頼に支払う',async(req,_p,tx)=>payRequest(tx,req.params.id),{body:empty,financial:true});
 route('POST','/v1/me/payment-requests/:id/cancel','consumer','支払依頼を取消',async(req,_p,tx)=>{const r=await tx.get('payment_requests',req.params.id);userOwn(tx,r);ensure(r.status==='created','INVALID_STATE');return tx.update('payment_requests',r.id,{status:'cancelled'});},{body:empty});
 route('POST','/v1/me/subscriptions/:id/consent','consumer','月額課金に同意',async(req,_p,tx)=>consent(tx,req.params.id,req.body),{body:B({accept:{type:'boolean'},source:S},['accept','source']),financial:true});
 route('POST','/v1/me/subscriptions/:id/cancel','consumer','継続課金の同意を撤回',async(req,_p,tx)=>subscriptionAction(tx,req.params.id,'cancel',true),{body:empty});
 route('POST','/v1/me/disputes','consumer','返金・購入トラブル申告',async(req,_p,tx)=>openDispute(tx,req.body),{body:B({order_id:S,subject:S,message:S},['order_id','message'])});
 route('POST','/v1/me/disputes/:id/messages','consumer','案件メッセージ',async(req,_p,tx)=>disputeMessage(tx,req.params.id,req.body),{body:B({message:S,attachment:{enum:['demo-receipt.txt','demo-shipping.txt']}},['message'])});
 route('GET','/v1/checkout/:id','consumer','支払内容を確認・セッション束縛',async(req,_p,tx)=>{const s=await tx.get('checkouts',req.params.id);ensure(!s.data.bound_user||s.data.bound_user===tx.ctx.user,'FORBIDDEN',undefined,403);const updated=await tx.update('checkouts',s.id,{data:{...s.data,bound_session:tx.ctx.session,bound_user:tx.ctx.user}});return {checkout:updated,authorization:(await tx.rows('authorizations',"AND data->>'checkout_id'=$3",[s.id]))[0]??null,order:await orderSummary(tx,s.parent_id!),merchant:sanitize(await tx.get('merchants',s.merchant_id!)),balances:await balances(tx,tx.ctx.user!),methods:await tx.rows('payment_methods',"AND user_id=$3 AND status='active' AND data->>'type'='card'",[tx.ctx.user])};});
 route('POST','/v1/checkout/:id/approve','consumer','利用者の支払承認',async(req,_p,tx)=>approve(tx,req.params.id,req.body),{body:B({source:S,challenge:{type:'boolean'}},['source','challenge']),financial:true});
 route('POST','/v1/checkout/:id/cancel','consumer','チェックアウトを取消',async(req,_p,tx)=>{const s=await tx.get('checkouts',req.params.id);ensure(s.status==='created','INVALID_STATE');ensure(s.data.bound_session===tx.ctx.session,'FORBIDDEN',undefined,403);return tx.update('checkouts',s.id,{status:'cancelled'});},{body:empty});
 route('POST','/v1/oauth/token','public','client_credentials トークン',async(req)=>{
  const r=(await pool.query("SELECT c.*,w.generation AS current_generation FROM credentials c JOIN demo_workspaces w ON w.id=c.workspace_id WHERE c.data->>'client_id'=$1 AND c.status='active'",[req.body.client_id])).rows[0];
  ensure(r&&r.generation===r.current_generation&&r.data.secret_hash===hash(req.body.client_secret),'UNAUTHENTICATED',undefined,401);const selected=req.body.scope?req.body.scope.split(' '):r.data.scopes;ensure(selected.every((s:string)=>r.data.scopes.includes(s)),'FORBIDDEN',undefined,403);
  const token=randomToken();await pool.query('INSERT INTO access_tokens(id,workspace_id,generation,credential_id,credential_version,scopes,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[hash(token),r.workspace_id,r.generation,r.id,r.version,selected,new Date(Date.now()+600000)]);return {access_token:token,token_type:'Bearer',expires_in:600,scope:selected.join(' ')};
 },{body:B({grant_type:{const:'client_credentials'},client_id:S,client_secret:S,scope:S},['grant_type','client_id','client_secret'])});
 route('POST','/v1/orders','merchant','決済注文の作成',async(req,_p,tx)=>createOrder(tx,req.body),{scope:'orders:write',body:orderSchema,financial:true});
 route('GET','/v1/orders','merchant','決済注文一覧',async(req,_p,tx)=>paged(tx,'orders',req.query),{scope:'orders:read'});
 route('GET','/v1/orders/:id','merchant','注文と各決済の詳細',async(req,_p,tx)=>{merchantOwn(tx,await tx.get('orders',req.params.id));return orderSummary(tx,req.params.id);},{scope:'orders:read'});
 route('POST','/v1/orders/:id/cancel','merchant','未処理注文を取消',async(req,_p,tx)=>{const o=await tx.get('orders',req.params.id);merchantOwn(tx,o);ensure(o.status==='created'&&!(await tx.rows('authorizations','AND parent_id=$3',[o.id])).length,'INVALID_STATE');for(const s of await tx.rows('checkouts','AND parent_id=$3',[o.id]))await tx.update('checkouts',s.id,{status:'cancelled'});return tx.update('orders',o.id,{status:'cancelled'});},{scope:'orders:write',body:empty,financial:true});
 route('POST','/v1/checkout-sessions','merchant','承認セッションを作成',async(req,_p,tx)=>createCheckout(tx,req.body),{scope:'orders:write',body:B({order_id:S,return_url:S,cancel_url:S},['order_id','return_url','cancel_url']),financial:true});
 for(const [path,table] of [['checkout-sessions','checkouts'],['authorizations','authorizations'],['captures','captures'],['refunds','refunds'],['payouts','payouts']] as const)route('GET',`/v1/${path}/:id`,'merchant',`${path} 詳細`,async(req,_p,tx)=>{const r=await tx.get(table,req.params.id);merchantOwn(tx,r);const safe=sanitize(r);if(table==='checkouts')safe.data={expires_at:r.data.expires_at,order_id:r.parent_id};return safe;},{scope:'payments:read'});
 route('POST','/v1/authorizations/:id/capture','merchant','全額・部分売上確定',async(req,_p,tx)=>capture(tx,req.params.id,req.body),{scope:'payments:write',body:B({amount:M,final_capture:{type:'boolean'}},['amount']),financial:true});
 route('POST','/v1/authorizations/:id/void','merchant','未確定残額を解放',async(req,_p,tx)=>voidAuthorization(tx,req.params.id),{scope:'payments:write',body:empty,financial:true});
 route('POST','/v1/captures/:id/refunds','merchant','元支払元へ全額・部分返金',async(req,_p,tx)=>refund(tx,req.params.id,req.body),{scope:'refunds:write',body:B({amount:M,reason:S},['amount']),financial:true});
 route('GET','/v1/balances','merchant','加盟店残高',async(_r,_p,tx)=>balances(tx,tx.ctx.merchant!),{scope:'balances:read'});
 route('GET','/v1/transactions','merchant','加盟店明細・CSV',async(req,reply,tx)=>history(req,reply,tx,tx.ctx.merchant!),{scope:'balances:read'});
 route('POST','/v1/payouts','merchant','加盟店模擬出金',async(req,_p,tx)=>payout(tx,req.body,true),{scope:'payouts:write',body:moneyBody,financial:true});
 route('POST','/v1/merchant/topups','merchant','加盟店の模擬追加入金',async(req,_p,tx)=>topup(tx,req.body,true),{scope:'payouts:write',body:moneyBody,financial:true});
 route('GET','/v1/merchant/overview','merchant','加盟店業務概要',async(_r,_p,tx)=>{
  const merchant=await tx.get('merchants',tx.ctx.merchant!);const result:any={merchant:sanitize(merchant),role:tx.ctx.role,scopes:tx.ctx.scopes};
  if(tx.ctx.scopes.includes('balances:read'))result.balances=await balances(tx,merchant.id);
  const access:Partial<Record<Table,string>>={orders:'orders:read',authorizations:'payments:read',captures:'payments:read',refunds:'payments:read',payouts:'payouts:write',plans:'subscriptions:write',subscriptions:'subscriptions:write',webhook_endpoints:'webhooks:manage',webhook_deliveries:'webhooks:manage',credentials:'webhooks:manage',api_logs:'webhooks:manage',disputes:'payments:read',settlement_lots:'balances:read',billing_cycles:'subscriptions:write'};
  for(const [table,scope] of Object.entries(access))if(tx.ctx.scopes.includes(scope))result[table]=(await tx.rows(table as Table,'AND merchant_id=$3 ORDER BY created_at DESC LIMIT 100',[merchant.id])).map(sanitize);
  return result;
 });
 route('PATCH','/v1/merchant/profile','merchant','店舗プロフィール・出金先設定',async(req,_p,tx)=>{const m=await tx.get('merchants',tx.ctx.merchant!);return tx.update('merchants',m.id,{data:{...m.data,display_name:req.body.display_name,contact:req.body.contact,payout_bank:req.body.payout_bank,logo:req.body.logo??m.data.logo}});},{roles:['owner'],idempotent:true,body:B({display_name:S,contact:S,logo:{type:'string',minLength:1,maxLength:4},payout_bank:{enum:['demo-bank-a','demo-bank-b']}},['display_name','contact','payout_bank'])});
 route('PATCH','/v1/merchant/return-urls','merchant','戻り先URL登録',async(req,_p,tx)=>{const validate=(s:string)=>{let u;try{u=new URL(s);}catch{return false;}return !u.username&&!u.password&&!u.hash&&(u.protocol==='https:'||config.local&&u.origin===config.storeUrl);};ensure(req.body.return_urls.every(validate)&&req.body.cancel_urls.every(validate));const m=await tx.get('merchants',tx.ctx.merchant!);return tx.update('merchants',m.id,{data:{...m.data,...req.body}});},{roles:['owner','developer'],idempotent:true,body:B({return_urls:{type:'array',items:S,maxItems:10},cancel_urls:{type:'array',items:S,maxItems:10}},['return_urls','cancel_urls'])});
 route('POST','/v1/merchant/applications','merchant','加盟店アプリの登録',async(req,_p,tx)=>credentialCreate(tx,req.body),{idempotent:true,body:B({name:S,scopes:{type:'array',items:{enum:[...scopes]}}},['name','scopes'])});
 for(const action of ['rotate','revoke'])route('POST',`/v1/merchant/applications/:id/${action}`,'merchant','API秘密鍵 '+action,async(req,_p,tx)=>{const c=await tx.get('credentials',req.params.id);merchantOwn(tx,c);ensure(action!=='rotate'||c.data.scopes.every((s:string)=>tx.ctx.scopes.includes(s)),'FORBIDDEN','自分にない権限の秘密鍵を取得することはできません。',403);const secret=randomToken();const r=await tx.update('credentials',c.id,{status:action==='revoke'?'revoked':'active',data:{...c.data,secret_hash:hash(secret)}});await tx.audit('credential.'+action,c.id,'加盟店による変更');return {...sanitize(r),...(action==='rotate'?{client_secret:secret}:{})};},{roles:['owner','developer'],idempotent:true,body:empty});
 route('POST','/v1/payment-links','merchant','固定金額支払リンク',async(req,_p,tx)=>{const n=amount(req.body.amount);const r=await tx.create('orders',{merchant_id:tx.ctx.merchant,owner_id:tx.ctx.merchant,business_key:'link:'+randomUUID(),amount:String(n),status:'created',data:{description:req.body.description,items:[{name:req.body.description,quantity:1,unit_amount:money(n)}],payment_link:true,expires_at:new Date(tx.now().getTime()+Number(req.body.expires_minutes??30)*60000).toISOString()}});return {...r,url:config.portalUrl+'/pay/'+r.id};},{scope:'orders:write',body:B({amount:M,description:S,expires_minutes:{type:'integer',minimum:1,maximum:1440}},['amount','description']),financial:true});
 route('GET','/v1/payment-links','merchant','支払リンク一覧',async(req,_p,tx)=>({data:(await tx.rows('orders',"AND merchant_id=$3 AND data->>'payment_link'='true'",[tx.ctx.merchant])).map(r=>({...r,url:config.portalUrl+'/pay/'+r.id}))}),{scope:'orders:read'});
 route('POST','/v1/payment-links/:id/deactivate','merchant','支払リンク無効化',async(req,_p,tx)=>{const r=await tx.get('orders',req.params.id);merchantOwn(tx,r);ensure(r.data.payment_link&&r.status==='created','INVALID_STATE');return tx.update('orders',r.id,{status:'cancelled'});},{scope:'orders:write',idempotent:true,body:empty});
 route('POST','/v1/checkout/payment-links/:id/open','consumer','支払リンクの確認画面を開く',async(req,_p,tx)=>{const o=await tx.get('orders',req.params.id);ensure(o.data.payment_link&&o.status==='created','INVALID_STATE');ensure(new Date(o.data.expires_at)>tx.now(),'EXPIRED');const s=await tx.create('checkouts',{merchant_id:o.merchant_id,parent_id:o.id,amount:o.amount,status:'created',data:{order_id:o.id,expires_at:o.data.expires_at,return_url:config.portalUrl+'/wallet',cancel_url:config.portalUrl+'/wallet',nonce:randomToken()}});return {checkout_url:config.portalUrl+'/checkout/'+s.id};},{body:empty});
 route('POST','/v1/webhook-endpoints','merchant','Webhook通知先登録',async(req,_p,tx)=>endpointCreate(tx,req.body),{scope:'webhooks:manage',idempotent:true,body:B({url:S,events:{type:'array',items:S}},['url','events'])});
 route('PATCH','/v1/webhook-endpoints/:id','merchant','Webhook通知先更新',async(req,_p,tx)=>{const e=await tx.get('webhook_endpoints',req.params.id);merchantOwn(tx,e);await webhookAddress(req.body.url);return sanitize(await tx.update('webhook_endpoints',e.id,{data:{...e.data,url:req.body.url,events:req.body.events}}));},{scope:'webhooks:manage',idempotent:true,body:B({url:S,events:{type:'array',items:S}},['url','events'])});
 route('DELETE','/v1/webhook-endpoints/:id','merchant','Webhook通知停止',async(req,_p,tx)=>{const e=await tx.get('webhook_endpoints',req.params.id);merchantOwn(tx,e);return sanitize(await tx.update('webhook_endpoints',e.id,{status:'disabled'}));},{scope:'webhooks:manage',idempotent:true});
 route('POST','/v1/webhook-endpoints/:id/rotate-secret','merchant','署名鍵更新・旧鍵は24時間移行',async(req,_p,tx)=>{const e=await tx.get('webhook_endpoints',req.params.id);merchantOwn(tx,e);const secret=randomToken();const r=await tx.update('webhook_endpoints',e.id,{data:{...e.data,previous_secret_encrypted:e.data.secret_encrypted,previous_valid_until:new Date(Date.now()+86400000).toISOString(),secret_encrypted:encrypt(secret)}});return {...sanitize(r),webhook_secret:secret};},{scope:'webhooks:manage',idempotent:true,body:empty});
 route('POST','/v1/webhook-endpoints/:id/test','merchant','テスト通知',async(req,_p,tx)=>{const e=await tx.get('webhook_endpoints',req.params.id);merchantOwn(tx,e);return tx.event('webhook.test',e);},{scope:'webhooks:manage',idempotent:true,body:empty});
 route('POST','/v1/webhook-deliveries/:id/retry','merchant','同一イベントを再配信',async(req,_p,tx)=>{const d=await tx.get('webhook_deliveries',req.params.id);merchantOwn(tx,d);return tx.create('webhook_deliveries',{merchant_id:d.merchant_id,parent_id:d.parent_id,status:'pending',data:{endpoint_id:d.data.endpoint_id,event_id:d.data.event_id,attempt:1,run_at:tx.now().toISOString(),manual:true}});},{scope:'webhooks:manage',idempotent:true,body:empty});
 route('POST','/v1/plans','merchant','月額JPYプラン',async(req,_p,tx)=>plan(tx,req.body),{scope:'subscriptions:write',body:B({name:S,amount:M,interval:{const:'month'}},['name','amount','interval']),financial:true});
 route('POST','/v1/subscriptions','merchant','同意待ち購読を作成',async(req,_p,tx)=>subscription(tx,req.body),{scope:'subscriptions:write',body:B({plan_id:S},['plan_id']),financial:true});
 for(const action of ['pause','resume','cancel'])route('POST',`/v1/subscriptions/:id/${action}`,'merchant','購読 '+action,async(req,_p,tx)=>subscriptionAction(tx,req.params.id,action),{scope:'subscriptions:write',idempotent:true,body:empty});
 route('POST','/v1/disputes/:id/messages','merchant','購入案件に回答',async(req,_p,tx)=>disputeMessage(tx,req.params.id,req.body),{scope:'payments:read',roles:['owner','support','finance','api'],idempotent:true,body:B({message:S,attachment:{enum:['demo-receipt.txt','demo-shipping.txt']}},['message'])});
 for(const [path,table,scope] of [['payouts','payouts','payouts:write'],['webhook-endpoints','webhook_endpoints','webhooks:manage'],['webhook-deliveries','webhook_deliveries','webhooks:manage'],['plans','plans','subscriptions:write'],['subscriptions','subscriptions','subscriptions:write'],['disputes','disputes','payments:read']] as const)route('GET',`/v1/${path}`,'merchant',`${path} 一覧`,async(req,_p,tx)=>paged(tx,table,req.query),{scope});
 route('GET','/v1/disputes/:id/messages','session','案件メッセージ履歴',async(req,_p,tx)=>{const d=await tx.get('disputes',req.params.id);ensure(tx.ctx.role==='admin'||d.user_id===tx.ctx.user||d.merchant_id===tx.ctx.merchant,'RESOURCE_NOT_FOUND',undefined,404);return {data:await tx.rows('dispute_messages','AND parent_id=$3 ORDER BY created_at',[d.id])};});
 route('GET','/v1/admin/overview','admin','運営調査の概要',async(req,_p,tx)=>{const result:any={now:tx.now(),settings:tx.workspace.settings,reconciliation:await reconciliation(tx),counts:(await tx.db.query("SELECT (SELECT count(*) FROM orders WHERE workspace_id=$1 AND generation=$2)::integer AS orders,(SELECT count(*) FROM provider_attempts WHERE workspace_id=$1 AND generation=$2 AND status='unknown')::integer AS provider_attempts,(SELECT count(*) FROM webhook_deliveries WHERE workspace_id=$1 AND generation=$2 AND status IN ('failed','dead_letter'))::integer AS webhook_deliveries,(SELECT count(*) FROM risk_reviews WHERE workspace_id=$1 AND generation=$2 AND status='pending')::integer AS risk_reviews",[tx.ctx.workspace,tx.ctx.generation])).rows[0]};for(const table of ['users','merchants','orders','authorizations','captures','refunds','payouts','provider_attempts','outbox','jobs','webhook_deliveries','risk_reviews','audit_logs','disputes'] as const)result[table]=(await tx.rows(table,'ORDER BY created_at DESC LIMIT 100')).map(sanitize);return result;});
 route('GET','/v1/admin/search','admin','横断検索',async(req,_p,tx)=>{ensure(tables.includes(req.query.table),'INVALID_REQUEST');return paged(tx,req.query.table,req.query,'all');});
 route('GET','/v1/admin/ledger','admin','台帳整合性レポート',async(_r,_p,tx)=>reconciliation(tx));
 route('POST','/v1/admin/accounts/:id/review','admin','模擬審査・能力別制限',async(req,_p,tx)=>{const table=req.body.type==='merchant'?'merchants':'users';const r=await tx.get(table,req.params.id);ensure(req.body.reason.trim().length>=3);const data={...r.data,capabilities:{...r.data.capabilities,...req.body.capabilities},restriction_reason:req.body.reason,...(table==='users'?{kyc:req.body.review}:{review:req.body.review})};const updated=await tx.update(table,r.id,{data});await tx.audit('account.review',r.id,req.body.reason,sanitize(r).data,sanitize(updated).data);if(Object.values(req.body.capabilities??{}).some(v=>v===false))await tx.event('account.restricted',{...updated,user_id:table==='users'?r.id:null,merchant_id:table==='merchants'?r.id:null});return sanitize(updated);},{body:B({type:{enum:['user','merchant']},reason:S,review:{enum:['unsubmitted','pending','verified','correction_required','approved']},capabilities:{type:'object',additionalProperties:false,properties:Object.fromEntries(capabilities.map(c=>[c,{type:'boolean'}]))}},['type','reason','review','capabilities'])});
 route('POST','/v1/admin/adjustments','admin','理由と対向勘定を伴う調整仕訳',async(req,_p,tx)=>{ensure(req.body.reason.trim().length>=3&&req.body.counter_account==='mock_external');const n=amount(req.body.amount);const r=await tx.get(req.body.type==='merchant'?'merchants':'users',req.body.owner_id);const reference=randomUUID();const lines=req.body.direction==='credit'?[debit('platform','external',n),credit(r.id,'available',n)]:[debit(r.id,'available',n),credit('platform','external',n)];const id=await journal(tx,'adjustment:'+reference,req.body.reason,lines,reference);await tx.audit('ledger.adjustment',id,req.body.reason,{},req.body);return {id,status:'succeeded'};},{body:B({amount:M,owner_id:S,type:{enum:['user','merchant']},direction:{enum:['credit','debit']},counter_account:{const:'mock_external'},reason:S},['amount','owner_id','type','direction','counter_account','reason']),financial:true});
 route('PATCH','/v1/admin/settings','admin','模擬手数料・上限の設定',async(req,_p,tx)=>{ensure(req.body.reason.trim().length>=3);const {reason,...settings}=req.body;await tx.db.query('UPDATE demo_workspaces SET settings=settings||$2::jsonb WHERE id=$1',[tx.ctx.workspace,settings]);await tx.audit('settings.update',tx.ctx.workspace,reason,tx.workspace.settings,settings);return settings;},{body:B({fee_bps:{type:'string',pattern:'^[0-9]{1,3}$'},fee_fixed:{type:'string',pattern:'^[0-9]{1,3}$'},limit:{type:'string',pattern:'^[1-9][0-9]{0,7}$'},subscription_limit:{type:'string',pattern:'^[1-9][0-9]{0,5}$'},settlement_seconds:{type:'string',pattern:'^[0-9]{1,6}$'},reason:S},['reason'])});
 route('POST','/v1/admin/risk-reviews/:id/resolve','admin','手動審査の記録',async(req,_p,tx)=>{const r=await tx.get('risk_reviews',req.params.id);ensure(req.body.reason.trim().length>=3);const out=await tx.update('risk_reviews',r.id,{status:'resolved',data:{...r.data,resolution:req.body.reason}});await tx.audit('risk.resolve',r.id,req.body.reason);return out;},{body:B({reason:S},['reason'])});
 route('POST','/v1/admin/disputes/:id/resolve','admin','購入トラブルを仲介',async(req,_p,tx)=>{const d=await tx.get('disputes',req.params.id);await disputeMessage(tx,d.id,{message:req.body.reason});const r=await tx.update('disputes',d.id,{status:'resolved'});await tx.audit('dispute.resolve',d.id,req.body.reason);await tx.event('dispute.updated',r);return r;},{body:B({reason:S},['reason'])});
 route('POST','/v1/demo/clock','session','workspace業務時計を進める',async(req,_p,tx)=>{const seconds=req.body.seconds;await tx.db.query('UPDATE demo_workspaces SET clock_offset=clock_offset+$2 WHERE id=$1',[tx.ctx.workspace,seconds*1000]);await tx.audit('demo.clock',tx.ctx.workspace,`${seconds}秒進める`);return {now:new Date(tx.now().getTime()+seconds*1000)};},{body:B({seconds:{type:'integer',minimum:0,maximum:34560000}},['seconds'])});
 route('GET','/v1/demo/inspect','session','現在のデモ処理を調査',async(_r,_p,tx)=>({workspace_id:tx.ctx.workspace,generation:tx.ctx.generation,role:tx.ctx.role,balances:await balances(tx,tx.ctx.merchant??tx.ctx.user!),authorizations:await tx.rows('authorizations',tx.ctx.merchant?'AND merchant_id=$3':'AND user_id=$3',[tx.ctx.merchant??tx.ctx.user]),provider_attempts:await tx.rows('provider_attempts','ORDER BY created_at DESC LIMIT 30'),jobs:await tx.rows('jobs','ORDER BY created_at DESC LIMIT 30'),outbox:await tx.rows('outbox','ORDER BY created_at DESC LIMIT 30'),deliveries:(await tx.rows('webhook_deliveries','ORDER BY created_at DESC LIMIT 30')).map(sanitize),api_logs:await tx.rows('api_logs','ORDER BY created_at DESC LIMIT 50'),reconciliation:await reconciliation(tx)}));
 route('POST','/v1/demo/scenarios','session','特定operationの模擬結果を設定',async(req,_p,tx)=>{const a=await tx.get('provider_attempts',req.body.attempt_id);ensure(!['succeeded','failed'].includes(a.status),'INVALID_STATE','完了した操作の結果は変更できません。');const old=(await tx.rows('scenarios','AND parent_id=$3',[a.id]))[0];if(old)return tx.update('scenarios',old.id,{data:{mode:req.body.mode}});return tx.create('scenarios',{parent_id:a.id,data:{mode:req.body.mode}});},{body:B({attempt_id:S,mode:{enum:['success','decline','pending','timeout_success','crash_after_success']}},['attempt_id','mode'])});
 route('POST','/v1/demo/store-handoff','session','サンプルECへの一度限りの接続コード',async(_r,_p,tx)=>{const h=(await tx.rows('store_handoffs',"AND status='available' ORDER BY created_at DESC"))[0];ensure(h,'INVALID_STATE','EC接続済みです。既存のECセッションを利用してください。');const code=randomToken();await tx.update('store_handoffs',h.id,{data:{...h.data,claim_hash:hash(code),expires_at:new Date(Date.now()+300000).toISOString()}});return {code,store_url:config.storeUrl};},{body:empty});
 route('POST','/v1/demo/claim-store','public','ECサーバーが接続コードを交換',async(req)=>{const h=(await pool.query("SELECT h.* FROM store_handoffs h JOIN demo_workspaces w ON w.id=h.workspace_id AND w.generation=h.generation WHERE h.data->>'claim_hash'=$1 AND h.status='available'",[hash(req.body.code)])).rows[0];ensure(h&&new Date(h.data.expires_at)>new Date(),'UNAUTHENTICATED',undefined,401);return transaction({workspace:h.workspace_id,generation:h.generation,actor:'store-bootstrap',role:'system',scopes:[],requestId:req.id},async tx=>{const current=await tx.get('store_handoffs',h.id);ensure(current.status==='available','INVALID_STATE');await tx.update('store_handoffs',h.id,{status:'claimed'});return {workspace_id:h.workspace_id,generation:h.generation,merchant_id:h.merchant_id,client_id:h.data.client_id,client_secret:decrypt(h.data.store_secret),webhook_secret:decrypt(h.data.webhook_secret)};});},{body:B({code:S},['code'])});
 // The outbound API call deliberately happens outside a workspace transaction.
 app.post('/v1/merchant/playground',{schema:{summary:'許可されたAPIをデモ資格情報で実行',tags:['merchant'],security:[{sessionCookie:[]}],body:B({method:{enum:['GET','POST']},path:{enum:['/v1/orders','/v1/balances','/v1/webhook-deliveries']},body:{type:'object'},idempotency_key:S},['method','path','idempotency_key']),response:{200:{type:'object',required:['status','latency_ms','request_id','response','curl','curl_powershell'],properties:{status:{type:'integer'},latency_ms:{type:'integer'},request_id:{type:['string','null']},response:{type:'object',additionalProperties:true},curl:{type:'string',description:'POSIX shell example. Set EXW_ACCESS_TOKEN from POST /v1/oauth/token; the token itself is never embedded.'},curl_powershell:{type:'string',description:'Windows PowerShell / pwsh example using curl.exe and $env:EXW_ACCESS_TOKEN.'}}},400:errorSchema,401:errorSchema,403:errorSchema,429:errorSchema}}},async(req:any,reply)=>{
  const {ctx,csrf}=await sessionContext(req.cookies.exw_session??'',req.id);ensure(req.headers.origin===config.portalUrl&&req.headers['x-csrf-token']===csrf,'FORBIDDEN',undefined,403);ensure(ctx.merchant&&['owner','developer'].includes(ctx.role),'FORBIDDEN',undefined,403);req.ctx=ctx;await limitActor(req,reply);
  const scope=req.body.path==='/v1/orders'?(req.body.method==='POST'?'orders:write':'orders:read'):req.body.path==='/v1/balances'?'balances:read':'webhooks:manage';ensure(ctx.scopes.includes(scope)&&!(req.body.method==='POST'&&req.body.path!=='/v1/orders'),'FORBIDDEN',undefined,403);
  const credentials=await transaction(ctx,async tx=>{let c=(await tx.rows('credentials',"AND merchant_id=$3 AND data->>'internal_playground'='true' AND owner_id=$4 AND status='active'",[ctx.merchant,ctx.actor]))[0];if(!c){const secret=randomToken();c=await tx.create('credentials',{merchant_id:ctx.merchant,owner_id:ctx.actor,data:{name:'API Playground',client_id:'exw_'+randomUUID(),secret_hash:hash(secret),secret_encrypted:encrypt(secret),internal_playground:true,scopes:ctx.scopes}});}return {client_id:c.data.client_id,client_secret:decrypt(c.data.secret_encrypted)};});
  const start=performance.now();const tr=await fetch(config.apiInternalUrl+'/v1/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({grant_type:'client_credentials',...credentials,scope}),signal:AbortSignal.timeout(5000)});const token=await tr.json();ensure(tr.ok,'UNAUTHENTICATED',undefined,401);
  const response=await fetch(config.apiInternalUrl+req.body.path,{method:req.body.method,headers:{Authorization:'Bearer '+token.access_token,'Content-Type':'application/json','Idempotency-Key':req.body.idempotency_key},body:req.body.method==='POST'?JSON.stringify(req.body.body):undefined,signal:AbortSignal.timeout(5000)});
  const examples=curlExamples({method:req.body.method,url:config.apiUrl+req.body.path,idempotencyKey:req.body.idempotency_key,body:req.body.body});
  return {status:response.status,latency_ms:Math.round(performance.now()-start),request_id:response.headers.get('x-request-id'),response:await response.json(),curl:examples.posix,curl_powershell:examples.powershell};
 });
 async function history(req:any,reply:any,tx:Tx,owner:string){
  const params:any[]=[tx.ctx.workspace,tx.ctx.generation,owner];let where='';
  if(req.query.q){params.push('%'+String(req.query.q).slice(0,100)+'%');where+=` AND e.description ILIKE $${params.length}`;}
  for(const [key,op] of [['from','>='],['to','<=']])if(req.query[key]){ensure(!isNaN(Date.parse(req.query[key])));params.push(req.query[key]);where+=` AND e.created_at${op}$${params.length}::timestamptz`;}
  if(req.query.cursor){let c;try{c=JSON.parse(Buffer.from(req.query.cursor,'base64url').toString());}catch{throw new DomainError('INVALID_REQUEST');}ensure(c&&typeof c.line==='string'&&/^\d+$/.test(c.line)&&!isNaN(Date.parse(c.at)));params.push(c.at,c.line);where+=` AND (e.created_at,l.id)<($${params.length-1}::timestamptz,$${params.length}::bigint)`;}
  const limit=req.query.format==='csv'?1000:Math.min(100,Math.max(1,Math.trunc(Number(req.query.limit)||25)));
  const result=(await tx.db.query(`SELECT e.id,l.id::text AS line_id,e.created_at,e.description,e.reference_id,e.business_event,l.side,l.amount::text,l.currency,a.kind,a.normal_side FROM journal_entries e JOIN journal_lines l ON (l.workspace_id,l.generation,l.journal_id)=(e.workspace_id,e.generation,e.id) JOIN ledger_accounts a ON (a.workspace_id,a.generation,a.id)=(l.workspace_id,l.generation,l.account_id) WHERE e.workspace_id=$1 AND e.generation=$2 AND a.owner_id=$3 ${where} ORDER BY e.created_at DESC,l.id DESC LIMIT ${limit+1}`,params)).rows;
  if(req.query.format==='csv')return reply.type('text/csv; charset=utf-8').header('Content-Disposition','attachment; filename="express-wallet-transactions.csv"').send(csv(result.slice(0,limit)));
  const last=result[limit-1];return {data:result.slice(0,limit),next_cursor:result.length>limit?Buffer.from(JSON.stringify({at:last.created_at,line:last.line_id})).toString('base64url'):null};
 }
 registerExtensions(route,paged);
 await app.ready();return app;
}
