import {randomUUID} from 'node:crypto';
import {type Tx,type Table} from '../../../packages/database/src/index.ts';
import {bodySchema as B,moneySchema as M,stringSchema as S} from '../../../packages/contracts/src/index.ts';
import {ensure,amount,csv,DomainError} from '../../../packages/domain/src/index.ts';
import {journal,type AccountKind} from '../../../packages/database/src/ledger.ts';
import {sanitize,merchantOwn,userOwn} from './security.ts';
import {disputeMessage} from './services.ts';
import {demoDocuments} from '../../../packages/testkit/src/documents.ts';
type Register=(method:string,url:string,auth:any,title:string,fn:(req:any,reply:any,tx:Tx)=>Promise<any>,options?:any)=>void;
export function registerExtensions(route:Register,paged:(tx:Tx,table:Table,q:any,scope:'merchant'|'user'|'all')=>Promise<any>){
 route('POST','/v1/admin/disputes/:id/messages','admin','案件への仲介メッセージとデモ資料',async(req,_p,tx)=>disputeMessage(tx,req.params.id,req.body),{body:B({message:S,attachment:{enum:Object.keys(demoDocuments)}},['message'])});
 route('GET','/v1/disputes/:id/materials/:filename','session','案件に添付された許可デモ資料',async(req,_p,tx)=>{const d=await tx.get('disputes',req.params.id);ensure(tx.ctx.role==='admin'||d.user_id===tx.ctx.user||d.merchant_id===tx.ctx.merchant,'RESOURCE_NOT_FOUND',undefined,404);const content=demoDocuments[req.params.filename];ensure(content&&(await tx.rows('dispute_messages',"AND parent_id=$3 AND data->>'attachment'=$4",[d.id,req.params.filename])).length,'RESOURCE_NOT_FOUND',undefined,404);return {filename:req.params.filename,content,content_type:'text/plain',sample:true};});
 route('GET','/v1/admin/journals/:id','admin','仕訳と勘定の詳細',async(req,_p,tx)=>{const e=(await tx.db.query('SELECT id,business_event,description,reference_id,created_at FROM journal_entries WHERE workspace_id=$1 AND generation=$2 AND id=$3',[tx.ctx.workspace,tx.ctx.generation,req.params.id])).rows[0];ensure(e,'RESOURCE_NOT_FOUND',undefined,404);const lines=(await tx.db.query('SELECT a.owner_id,a.kind,l.side,l.amount::text,l.currency FROM journal_lines l JOIN ledger_accounts a ON (a.workspace_id,a.generation,a.id)=(l.workspace_id,l.generation,l.account_id) WHERE l.workspace_id=$1 AND l.generation=$2 AND l.journal_id=$3',[tx.ctx.workspace,tx.ctx.generation,e.id])).rows;return {...e,lines};});
 route('GET','/v1/me/records/:table','consumer','利用者の一覧を検索・ページング',async(req,_p,tx)=>{ensure(['topups','transfers','payouts','payment_requests','subscriptions','notifications','disputes'].includes(req.params.table));return paged(tx,req.params.table,req.query,'user');});
 route('GET','/v1/merchant/records/:table','merchant','加盟店の一覧を検索・ページング',async(req,_p,tx)=>{const permissions:Record<string,string>={orders:'orders:read',captures:'payments:read',refunds:'payments:read',authorizations:'payments:read',payouts:'payouts:write',subscriptions:'subscriptions:write',plans:'subscriptions:write',disputes:'payments:read',credentials:'webhooks:manage',webhook_deliveries:'webhooks:manage',api_logs:'webhooks:manage',settlement_lots:'balances:read',billing_cycles:'subscriptions:write'};const scope=permissions[req.params.table];ensure(scope&&tx.ctx.scopes.includes(scope),'FORBIDDEN',undefined,403);return paged(tx,req.params.table,req.query,'merchant');});
 route('GET','/v1/me/payment-requests/:id','consumer','支払依頼リンクの内容',async(req,_p,tx)=>{const r=await tx.get('payment_requests',req.params.id);const u=await tx.get('users',r.user_id!);return {...r,requester_name:u.data.name};});
 for(const [prefix,auth] of [['/v1/me','consumer'],['/v1','merchant']] as const)route('GET',prefix+'/operations/:id',auth,'受付済み操作を照会',async(req,_p,tx)=>{
  for(const table of ['topups','payouts','authorizations','captures','refunds','transfers'] as const){const r=(await tx.rows(table,'AND id=$3',[req.params.id]))[0];if(!r)continue;if(auth==='consumer')userOwn(tx,r);else merchantOwn(tx,r);return sanitize(r);}ensure(false,'RESOURCE_NOT_FOUND',undefined,404);
 },auth==='merchant'?{scope:'payments:read'}:{});
 route('GET','/v1/merchant/reports','merchant','期間内の日次売上・返金・手数料',async(req,reply,tx)=>{
  const from=req.query.from??new Date(tx.now().getTime()-30*86400000).toISOString(),to=req.query.to??tx.now().toISOString();ensure(!isNaN(Date.parse(from))&&!isNaN(Date.parse(to))&&new Date(from)<=new Date(to));
  const rows=(await tx.db.query(`WITH sales AS (SELECT (created_at AT TIME ZONE 'UTC')::date AS day,sum(amount)::text AS captured,sum((data->>'fee')::bigint)::text AS fees,count(*)::integer AS count FROM captures WHERE workspace_id=$1 AND generation=$2 AND merchant_id=$3 AND status='succeeded' AND created_at BETWEEN $4 AND $5 GROUP BY 1), returns AS (SELECT (updated_at AT TIME ZONE 'UTC')::date AS day,sum(amount)::text AS refunded FROM refunds WHERE workspace_id=$1 AND generation=$2 AND merchant_id=$3 AND status='succeeded' AND updated_at BETWEEN $4 AND $5 GROUP BY 1) SELECT coalesce(s.day,r.day)::text AS day,coalesce(s.captured,'0') AS captured,coalesce(s.fees,'0') AS fees,coalesce(r.refunded,'0') AS refunded,coalesce(s.count,0) AS count FROM sales s FULL JOIN returns r USING(day) ORDER BY day DESC`,[tx.ctx.workspace,tx.ctx.generation,tx.ctx.merchant,from,to])).rows;
  if(req.query.format==='csv')return reply.type('text/csv; charset=utf-8').send(csv(rows));return {currency:'JPY',from,to,data:rows};
 },{scope:'balances:read'});
 route('GET','/v1/admin/timeline/:id','admin','注文から台帳・通知まで追跡',async(req,_p,tx)=>{
  const order=await tx.get('orders',req.params.id);const auth=await tx.rows('authorizations','AND parent_id=$3',[order.id]);const aid=auth.map(a=>a.id);const captures=await tx.rows('captures','AND parent_id=ANY($3)',[aid]);const cid=captures.map(c=>c.id);const refunds=await tx.rows('refunds','AND parent_id=ANY($3)',[cid]);const ids=[order.id,...aid,...cid,...refunds.map(r=>r.id)];
  const events=await tx.rows('outbox','AND parent_id=ANY($3) ORDER BY created_at',[ids]);const deliveries=events.length?await tx.rows('webhook_deliveries','AND parent_id=ANY($3) ORDER BY created_at',[events.map(e=>e.id)]):[];
  const journals=(await tx.db.query('SELECT id,business_event,description,reference_id,created_at FROM journal_entries WHERE workspace_id=$1 AND generation=$2 AND reference_id=ANY($3) ORDER BY created_at,id',[tx.ctx.workspace,tx.ctx.generation,ids])).rows;
  const lines=journals.length?(await tx.db.query('SELECT l.journal_id,a.owner_id,a.kind,l.side,l.amount::text,l.currency FROM journal_lines l JOIN ledger_accounts a ON (a.workspace_id,a.generation,a.id)=(l.workspace_id,l.generation,l.account_id) WHERE l.workspace_id=$1 AND l.generation=$2 AND l.journal_id=ANY($3) ORDER BY l.id',[tx.ctx.workspace,tx.ctx.generation,journals.map(j=>j.id)])).rows:[];
  return {order,checkouts:await tx.rows('checkouts','AND parent_id=$3',[order.id]),authorizations:auth,captures,refunds,settlement_lots:await tx.rows('settlement_lots','AND parent_id=ANY($3)',[cid]),disputes:await tx.rows('disputes','AND parent_id=$3',[order.id]),billing_cycles:await tx.rows('billing_cycles','AND order_reference_id=$3',[order.id]),provider_attempts:await tx.rows('provider_attempts','AND parent_id=ANY($3)',[ids]),events,deliveries:deliveries.map(sanitize),journals:journals.map(j=>({...j,lines:lines.filter(l=>l.journal_id===j.id)}))};
 });
 route('GET','/v1/admin/journals','admin','仕訳の検索・cursorページング',async(req,_p,tx)=>{
  const params:any[]=[tx.ctx.workspace,tx.ctx.generation];let where='';
  if(req.query.q){params.push('%'+String(req.query.q).slice(0,100)+'%');where+=` AND (e.id||' '||e.business_event||' '||e.description||' '||coalesce(e.reference_id,'')) ILIKE $${params.length}`;}
  for(const [key,op] of [['from','>='],['to','<=']] as const)if(req.query[key]){ensure(!isNaN(Date.parse(req.query[key])));params.push(req.query[key]);where+=` AND e.created_at${op}$${params.length}::timestamptz`;}
  if(req.query.cursor){let c;try{c=JSON.parse(Buffer.from(req.query.cursor,'base64url').toString());}catch{throw new DomainError('INVALID_REQUEST');}ensure(c&&typeof c.id==='string'&&!isNaN(Date.parse(c.at)));params.push(c.at,c.id);where+=` AND (e.created_at,e.id)<($${params.length-1}::timestamptz,$${params.length})`;}
  const limit=Math.min(100,Math.max(1,Math.trunc(Number(req.query.limit)||25)));
  const rows=(await tx.db.query(`SELECT e.id,e.business_event,e.description,e.reference_id,e.created_at,coalesce(sum(l.amount) FILTER (WHERE l.side='debit'),0)::text AS amount,count(l.id)::integer AS lines FROM journal_entries e LEFT JOIN journal_lines l ON (l.workspace_id,l.generation,l.journal_id)=(e.workspace_id,e.generation,e.id) WHERE e.workspace_id=$1 AND e.generation=$2 ${where} GROUP BY e.id,e.business_event,e.description,e.reference_id,e.created_at ORDER BY e.created_at DESC,e.id DESC LIMIT ${limit+1}`,params)).rows;
  const last=rows[limit-1];return {data:rows.slice(0,limit),next_cursor:rows.length>limit?Buffer.from(JSON.stringify({at:last.created_at,id:last.id})).toString('base64url'):null};
 });
 route('POST','/v1/admin/webhook-deliveries/:id/retry','admin','運営者による通知の再配信（理由を監査）',async(req,_p,tx)=>{const d=await tx.get('webhook_deliveries',req.params.id);ensure(['failed','dead_letter','succeeded','cancelled'].includes(d.status),'INVALID_STATE','処理中の配信は再送できません。');ensure(req.body.reason.trim().length>=3);const r=await tx.create('webhook_deliveries',{merchant_id:d.merchant_id,parent_id:d.parent_id,status:'pending',data:{endpoint_id:d.data.endpoint_id,event_id:d.data.event_id,attempt:1,run_at:tx.now().toISOString(),manual:true,actor:'admin'}});await tx.audit('webhook.retry',d.id,req.body.reason,{},{delivery_id:r.id});return sanitize(r);},{idempotent:true,body:B({reason:S},['reason'])});
 route('POST','/v1/admin/jobs/:id/retry','admin','失敗ジョブの再試行（理由を監査）',async(req,_p,tx)=>{const j=await tx.get('jobs',req.params.id);ensure(['failed','pending'].includes(j.status),'INVALID_STATE');ensure(req.body.reason.trim().length>=3);const r=await tx.update('jobs',j.id,{status:'pending',data:{...j.data,tries:0,run_at:tx.now().toISOString()}});await tx.audit('job.retry',j.id,req.body.reason);return r;},{idempotent:true,body:B({reason:S},['reason'])});
 route('POST','/v1/admin/journals/:id/reverse','admin','調整仕訳を参照付き反対仕訳で訂正',async(req,_p,tx)=>{
  const e=(await tx.db.query('SELECT * FROM journal_entries WHERE workspace_id=$1 AND generation=$2 AND id=$3',[tx.ctx.workspace,tx.ctx.generation,req.params.id])).rows[0];ensure(e&&e.business_event.startsWith('adjustment:'),'INVALID_REQUEST','管理者調整仕訳のみ反対仕訳で訂正できます。決済は返金APIを使ってください。');ensure(req.body.reason.trim().length>=3);
  const lines=(await tx.db.query('SELECT a.owner_id,a.kind,l.side,l.amount::text FROM journal_lines l JOIN ledger_accounts a ON (a.workspace_id,a.generation,a.id)=(l.workspace_id,l.generation,l.account_id) WHERE l.workspace_id=$1 AND l.generation=$2 AND l.journal_id=$3',[tx.ctx.workspace,tx.ctx.generation,e.id])).rows;
  const id=await journal(tx,'reversal:'+e.id,req.body.reason,lines.map(l=>({owner:l.owner_id,kind:l.kind as AccountKind,side:l.side==='debit'?'credit':'debit',amount:BigInt(l.amount)})),e.id);await tx.audit('journal.reverse',id,req.body.reason,{original:e.id});return {id,status:'succeeded'};
 },{body:B({reason:S},['reason']),financial:true});
 route('POST','/v1/demo/worker','session','現在のworkspaceのジョブ取得を一時停止・再開',async(req,_p,tx)=>{await tx.db.query('UPDATE demo_workspaces SET settings=settings||$2::jsonb WHERE id=$1',[tx.ctx.workspace,{worker_paused:req.body.paused}]);await tx.audit('demo.worker',tx.ctx.workspace,req.body.paused?'ジョブ取得を一時停止':'ジョブ取得を再開');return {paused:req.body.paused};},{body:B({paused:{type:'boolean'}},['paused'])});
 route('POST','/v1/demo/jobs/:id/retry','session','失敗ジョブを再試行',async(req,_p,tx)=>{const j=await tx.get('jobs',req.params.id);ensure(['failed','pending'].includes(j.status),'INVALID_STATE');return tx.update('jobs',j.id,{status:'pending',data:{...j.data,tries:0,run_at:tx.now().toISOString()}});},{body:B({})});
}
