import {readFileSync,writeFileSync} from 'node:fs';
function edit(file,from,to){const text=readFileSync(file,'utf8');if(!text.includes(from))throw Error('Anchor missing '+file);writeFileSync(file,text.replace(from,to));}
edit('apps/portal/components/portal.tsx','import {Developer,Admin,Demo}', 'import {Developer,Admin,Demo,DailyReports}');
edit('apps/portal/components/portal.tsx','</small>{error&&<div role="alert"',`</small><details className="login-details"><summary>{t('作成済みアカウントでログイン','Sign in to an existing account')}</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const s=await request('/v1/auth/login','POST',{email:f.get('email'),password:f.get('password')});setSession(s);go('/wallet');}catch(e:any){setError(e.message);}}}><label className="form-field">{t('デモメール','Demo email')}<input name="email" type="email" required autoComplete="username"/></label><label className="form-field">{t('パスワード','Password')}<input name="password" type="password" required autoComplete="current-password"/></label><button className="secondary" type="submit">{t('ログイン','Sign in')}</button></form></details>{error&&<div role="alert"`);
edit('apps/portal/components/portal.tsx',"{data.balances&&stats()}<section className=\"card\">", "{data.balances&&stats()}{data.balances&&<DailyReports request={request}/>}<section className=\"card\">");
edit('apps/portal/components/portal.tsx',"r.data.memo||'支払依頼'", "r.data.memo||'支払依頼'");
edit('apps/portal/components/portal.tsx',`<code>{r.id.slice(0,8)}</code>`, `<a className="text-button" href={'/request/'+r.id}>依頼リンク ↗</a>`);
edit('apps/portal/components/portal.tsx',`else if(area==='admin')d=`, `else if(area==='request')d={request:await request('/v1/me/payment-requests/'+section)};else if(area==='admin')d=`);
edit('apps/portal/components/portal.tsx',`{area==='pay'&&`, `{area==='request'&&data.request&&<section className="card checkout-card"><h2>{data.request.requester_name}さんからの支払依頼</h2><p>{data.request.data.memo}</p><Amount value={data.request.amount} className="stat-number"/><p>期限：{date(data.request.data.expires_at)}</p><BadgeStatus value={data.request.status}/><div className="toolbar"><button className="primary" disabled={data.request.status!=='created'||data.request.user_id===session.user.id} onClick={()=>simple('支払依頼に支払う','/v1/me/payment-requests/'+section+'/approve',data.request.requester_name+'さんへ'+data.request.amount+'円を送金します。',true)}>この依頼に支払う</button></div></section>}
 {area==='pay'&&`);
edit('apps/portal/components/workspaces.tsx',`<div className="button-stack"><button className="secondary" onClick={()=>act({title:'業務時計を進める'`, `<div className="button-stack"><button className="secondary" onClick={()=>simple('ジョブ取得を一時停止','/v1/demo/worker','新しいジョブ取得を止めます。すでに送信した操作は完了する場合があります。',false,{paused:true})}>ジョブ取得を一時停止</button><button className="secondary" onClick={()=>simple('ジョブ取得を再開','/v1/demo/worker','現在のデモの処理を再開します。',false,{paused:false})}>ジョブ取得を再開</button><button className="secondary" onClick={()=>act({title:'業務時計を進める'`);
edit('apps/portal/components/workspaces.tsx',"import {useState}","import {useState,useEffect}");
edit('apps/portal/next.config.ts',"reactStrictMode:true,", "reactStrictMode:true,devIndicators:false,");
