'use client';
import {useId,useState} from 'react';
import {useLanguage,tr} from '../../../packages/ui/src/i18n';
/**
 * Calls the same authenticated merchant API as ordinary captures; no success shortcut.
 * Labels are attached with htmlFor/id instead of wrapping the control, so the accessible
 * name of each field is only the label text (option text is not merged into it).
 */
export function ConcurrencyLab({request,authorizations}:{request:any;authorizations:any[]}){
 const en=useLanguage()==='en';const fieldId=useId();const authorizationField=fieldId+'-authorization',amountField=fieldId+'-amount',sameKeyField=fieldId+'-same-key';
 const [id,setId]=useState(''),[value,setValue]=useState('100'),[same,setSame]=useState(true),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[report,setReport]=useState<any>(null),[error,setError]=useState('');
 async function run(){setBusy(true);setError('');try{const before=await request('/v1/demo/inspect'),key=crypto.randomUUID();const results=await Promise.allSettled(Array.from({length:100},(_,i)=>request('/v1/authorizations/'+id+'/capture','POST',{amount:{currency:'JPY',value},final_capture:false},same?key:key+'-'+i)));const after=await request('/v1/demo/inspect');const succeeded=results.filter(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>[];setReport({requests:100,successful_responses:succeeded.length,unique_captures:new Set(succeeded.map(r=>r.value.id)).size,rejected:results.filter(r=>r.status==='rejected').map(r=>(r as PromiseRejectedResult).reason.code),before:{balances:before.balances,authorizations:before.authorizations},after:{balances:after.balances,authorizations:after.authorizations},ledger_ok:after.reconciliation.ok});setConfirm(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const open=authorizations.filter(a=>['authorized','partially_captured'].includes(a.status));
 return <section className="card"><h2>{en?'Concurrent capture experiment':'100並列の売上確定を試す'}</h2><p>{en?'First approve an order, then switch to its merchant. Each request uses the ordinary capture API.':'注文を承認してから、その加盟店へ切り替えて操作します。通常のcapture APIへ並列送信します。'}</p><form onSubmit={e=>{e.preventDefault();if(!confirm)setConfirm(true);else void run();}}>
  <div className="form-field"><label htmlFor={authorizationField}>{tr('オーソリ')}</label><select id={authorizationField} required value={id} disabled={busy} onChange={e=>{setId(e.target.value);setConfirm(false);}}><option value="">{en?'Select an authorization':'オーソリを選択'}</option>{open.map(a=><option key={a.id} value={a.id}>{a.id} · {a.amount} JPY</option>)}</select>{!open.length&&<small>{en?'No open authorization for this merchant yet.':'この加盟店に未確定のオーソリはまだありません。'}</small>}</div>
  <div className="form-field"><label htmlFor={amountField}>{en?'Amount per request (JPY)':'1要求の金額（円）'}</label><input id={amountField} required inputMode="numeric" pattern="[1-9][0-9]*" value={value} disabled={busy} onChange={e=>{setValue(e.target.value);setConfirm(false);}}/></div>
  <div className="form-field"><label htmlFor={sameKeyField}><input id={sameKeyField} type="checkbox" checked={same} disabled={busy} onChange={e=>{setSame(e.target.checked);setConfirm(false);}}/> {en?'Reuse one idempotency key':'同じ冪等キーを使用'}</label></div>
  {confirm&&<p role="status">{en?`Send 100 requests of ${value} JPY. ${same?'Only one capture should be created.':'Different keys can capture up to the remaining authorization.'}`:`${value}円の要求を100件送信します。${same?'同じ操作として1回だけ確定します。':'異なるキーでは残りの確保額まで複数回確定します。'}`}</p>}
  <button className="primary" disabled={busy||!id}>{busy?tr('処理中…'):confirm?tr('確認して実行'):tr('内容を確認')}</button></form>{error&&<p className="error" role="alert">{error}</p>}{report&&<pre aria-label={en?'Concurrency results':'並列要求の結果'}>{JSON.stringify(report,null,2)}</pre>}</section>;
}

export function ConcurrentApprovals({request}:{request:any}){
 const en=useLanguage()==='en';const fieldId=useId();const [ids,setIds]=useState(['','']),[preview,setPreview]=useState<any[]|null>(null),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[accepted,setAccepted]=useState(false);
 const checkoutId=(value:string)=>value.includes('://')?new URL(value).pathname.split('/').pop()!:value;
 async function review(){setBusy(true);setError('');try{const keys=ids.map(checkoutId);if(keys[0]===keys[1])throw Error(en?'Choose two different checkouts.':'異なるチェックアウトを指定してください。');const rows=await Promise.all(keys.map(id=>request('/v1/checkout/'+encodeURIComponent(id))));if(rows.some(r=>r.checkout.status!=='created'))throw Error(en?'Choose unapproved checkouts.':'未承認のチェックアウトを指定してください。');setPreview(rows);setAccepted(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function approveBoth(){if(!preview||!accepted)return;setBusy(true);setError('');try{const before=await request('/v1/demo/inspect'),results=await Promise.allSettled(preview.map(p=>request('/v1/checkout/'+p.checkout.id+'/approve','POST',{source:'wallet',challenge:true},crypto.randomUUID()))),after=await request('/v1/demo/inspect');setResult({before:before.balances,results:results.map(r=>r.status==='fulfilled'?{authorization_id:r.value.id,status:r.value.status}:{error:r.reason.code,message:r.reason.message}),after:after.balances,ledger_ok:after.reconciliation.ok});setPreview(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="card"><h2>{en?'Approve two payments concurrently':'同じ残高から2件を同時承認'}</h2><p>{en?'Create two orders in the sample store and copy their checkout URLs before approval. Review both merchants and amounts here. Payment source: wallet balance.':'サンプルECで2件の注文を作成し、承認前のチェックアウトURLを入力します。支払先・金額を確認してから、ウォレット残高で同時承認します。'}</p>{ids.map((id,i)=><div className="form-field" key={i}><label htmlFor={`${fieldId}-checkout-${i}`}>{en?'Checkout URL or ID':'チェックアウトURLまたはID'} {i+1}</label><input id={`${fieldId}-checkout-${i}`} value={id} disabled={busy} onChange={e=>{setIds(ids.map((v,k)=>i===k?e.target.value:v));setPreview(null);}}/></div>)}{!preview?<button className="secondary" disabled={busy||ids.some(id=>!id)} onClick={review}>{tr('内容を確認')}</button>:<><div className="confirmation">{preview.map(p=><p key={p.checkout.id}>{p.merchant.data.display_name} · {p.order.data.description} · <strong>{p.order.amount} JPY</strong></p>)}<label htmlFor={fieldId+'-accept'}><input id={fieldId+'-accept'} type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{en?'I approve both displayed payments using my wallet balance.':'表示した2件をウォレット残高で支払うことに同意します。'}</label></div><button className="primary" disabled={busy||!accepted} onClick={approveBoth}>{en?'Approve both concurrently':'両方を同時承認'}</button></>}{error&&<p role="alert" className="error">{error}</p>}{result&&<pre aria-label={en?'Concurrent approval results':'同時承認の結果'}>{JSON.stringify(result,null,2)}</pre>}</section>;
}
