'use client';
import {useState} from 'react';
import {useLanguage} from '../../../packages/ui/src/i18n';
import type {Action} from './portal';
export function Investigation({request,act,journals=[]}:{request:any;act:(a:Action)=>void;journals?:any[]}){
 const en=useLanguage()==='en';const [id,setId]=useState(''),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="card"><h2>{en?'Order timeline and journal corrections':'注文タイムライン・調整仕訳の訂正'}</h2><form className="toolbar" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{setResult(await request('/v1/admin/timeline/'+encodeURIComponent(id)));}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>{en?'ExPress order ID':'ExPress注文ID'}<input required value={id} onChange={e=>setId(e.target.value)}/></label><button className="secondary" disabled={busy}>{en?'Trace order':'注文を追跡'}</button></form>{error&&<p role="alert" className="error">{error}</p>}{result&&<pre aria-label={en?'Order timeline':'注文タイムライン'}>{JSON.stringify(result,null,2)}</pre>}{journals.filter(j=>j.business_event.startsWith('adjustment:')&&!journals.some(r=>r.business_event==='reversal:'+j.id)).map(j=><article className="credential" key={j.id}><div><strong>{j.description}</strong><small>{j.id}</small></div><button className="secondary" onClick={async()=>{try{const entry=await request('/v1/admin/journals/'+j.id),total=entry.lines.filter((l:any)=>l.side==='debit').reduce((s:bigint,l:any)=>s+BigInt(l.amount),0n);act({title:en?'Reverse adjustment':'調整仕訳の反対仕訳',description:(en?`Reverse ${total} JPY for journal ${j.id}. `:`仕訳 ${j.id} の ${total}円を反対仕訳で訂正します。`)+entry.lines.map((l:any)=>`${l.owner_id} / ${l.kind}: ${l.side} ${l.amount} JPY`).join(' · '),path:'/v1/admin/journals/'+j.id+'/reverse',financial:true,fields:[{key:'reason',label:en?'Reason':'理由',value:''}]});}catch(e:any){setError(e.message);}}}>{en?'Reverse with a reason':'理由を付けて訂正'}</button></article>)}</section>;
}
const snapshots=new Map<string,{before?:any;after?:any}>();
export function DemoSnapshots({request,scope}:{request:any;scope:string}){const en=useLanguage()==='en';const [before,setBefore]=useState<any>(snapshots.get(scope)?.before??null),[after,setAfter]=useState<any>(snapshots.get(scope)?.after??null),[error,setError]=useState('');const capture=async(set:(r:any)=>void)=>{try{const r=await request('/v1/demo/inspect');snapshots.set(scope,{...snapshots.get(scope),[set===setBefore?'before':'after']:r});set(r);setError('');}catch(e:any){setError(e.message);}};return <section className="card"><h2>{en?'Compare before and after':'操作前後を比較'}</h2><p>{en?'Take a snapshot, perform a scenario through the normal screens, then capture the result.':'操作前を保存し、通常画面でシナリオを実行した後、操作後を取得します。'}</p><div className="toolbar"><button className="secondary" onClick={()=>capture(setBefore)}>{en?'Save before':'操作前を保存'}</button><button className="secondary" onClick={()=>capture(setAfter)}>{en?'Fetch after':'操作後を取得'}</button></div>{error&&<p role="alert">{error}</p>}<div className="two-grid">{[before,after].map((r,i)=><div key={i}><h3>{i?(en?'After':'操作後'):(en?'Before':'操作前')}</h3>{r?<pre>{JSON.stringify({balances:r.balances,authorizations:r.authorizations,events:r.outbox,deliveries:r.deliveries,api_logs:r.api_logs,ledger:r.reconciliation},null,2)}</pre>:<p>{en?'No snapshot yet. Snapshots stay in this tab until it reloads.':'未取得です。'}</p>}</div>)}</div></section>;}
