'use client';
import {useEffect,useState} from 'react';
import {tr,useLanguage} from '../../../packages/ui/src/i18n';
import {csv} from '../../../packages/domain/src/index';
import {Amount,Badge,Empty} from '../../../packages/ui/src/index';
type Row=Record<string,any>;
export function downloadCsv(rows:Row[],name='express-wallet.csv'){const url=URL.createObjectURL(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function HistoryPager({endpoint,request,onData}:{endpoint:string;request:any;onData:(r:Row)=>void}){
 const en=useLanguage()==='en';const [q,setQ]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[cursors,setCursors]=useState<(string|null)[]>([null]),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const query=(cursor?:string|null)=>new URLSearchParams({q,limit:'100',...(from?{from:from+'T00:00:00.000Z'}:{}),...(to?{to:to+'T23:59:59.999Z'}:{}),...(cursor?{cursor}:{})});
 async function load(cursor:string|null=null){setBusy(true);setError('');try{const r=await request(endpoint+'?'+query(cursor));onData(r);setNext(r.next_cursor);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{setCursors([null]);void load();},[request,endpoint]);
 async function exportAll(){setBusy(true);setError('');try{const rows:Row[]=[];let cursor:string|null=null;do{const r:Row=await request(endpoint+'?'+query(cursor));rows.push(...r.data);cursor=r.next_cursor;if(rows.length>=10000&&cursor)throw Error(en?'More than 10,000 lines. Narrow the date range.':'10,000行を超えています。期間を絞ってください。');}while(cursor);downloadCsv(rows,'express-wallet-transactions.csv');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <><form className="toolbar" onSubmit={e=>{e.preventDefault();setCursors([null]);void load();}}><input aria-label={tr('取引を検索')} placeholder={tr('取引を検索')} value={q} onChange={e=>setQ(e.target.value)}/><input type="date" aria-label={tr('開始日')} value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" aria-label={tr('終了日')} value={to} onChange={e=>setTo(e.target.value)}/><small>UTC</small><button className="secondary compact" disabled={busy}>{tr('絞り込む')}</button><button type="button" className="secondary compact" disabled={busy} onClick={exportAll}>CSV</button></form><div className="toolbar"><button className="secondary compact" disabled={busy||cursors.length<=1} onClick={()=>{const c=cursors.slice(0,-1);setCursors(c);void load(c.at(-1));}}>{tr('前へ')}</button><span>{en?'Page':'ページ'} {cursors.length}</span><button className="secondary compact" disabled={busy||!next} onClick={()=>{setCursors([...cursors,next]);void load(next);}}>{tr('次へ')}</button>{busy&&<span role="status">{tr('処理中…')}</span>}</div>{error&&<p role="alert" className="error">{error}<button onClick={()=>load(cursors.at(-1))}>{tr('再試行')}</button></p>}</>;
}
/** One server cursor per page. Filtering and ordering are performed by the API. */
export function RecordBrowser({request,endpoint,onOpen}:{request:any;endpoint:string;onOpen?:(r:Row)=>void}){
 const lang=useLanguage(),en=lang==='en';const [q,setQ]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[result,setResult]=useState<Row>({data:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(true),[cursors,setCursors]=useState<(string|null)[]>([null]);
 async function load(cursor:string|null=null){setBusy(true);try{const query=new URLSearchParams({q,status,limit:'25',...(from?{from:new Date(from).toISOString()}:{}),...(to?{to:new Date(to+'T23:59:59').toISOString()}:{}),...(cursor?{cursor}:{})});setResult(await request(endpoint+(endpoint.includes('?')?'&':'?')+query));setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{setCursors([null]);void load();},[endpoint,request]);
 const exportPage=()=>{const records=result.data.map((r:Row)=>({id:r.id,reference:r.business_key??r.parent_id??'',status:r.status,currency:r.currency,amount:r.amount,created_at:r.created_at,description:r.data?.description??r.data?.name??r.data?.subject??r.data?.title??''}));const url=URL.createObjectURL(new Blob([csv(records)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='express-wallet-page.csv';a.click();URL.revokeObjectURL(url);};
 return <div><form className="toolbar" onSubmit={e=>{e.preventDefault();setCursors([null]);void load();}}><input aria-label={tr('検索文字列')} placeholder={tr('検索')} value={q} onChange={e=>setQ(e.target.value)}/><input aria-label={tr('状態')} placeholder={en?'Status, e.g. succeeded':'状態（例 succeeded）'} value={status} onChange={e=>setStatus(e.target.value)}/><input aria-label={tr('開始日')} type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label={tr('終了日')} type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="secondary compact" disabled={busy}>{tr('絞り込む')}</button><button type="button" className="secondary compact" onClick={exportPage} disabled={!result.data.length}>{en?'Export this page':'表示ページをCSV'}</button></form>{error&&<p role="alert" className="error">{error} <button onClick={()=>load(cursors.at(-1))}>{tr('再試行')}</button></p>}
 {busy?<p aria-live="polite">{tr('処理中…')}</p>:result.data.length?<div className="table-scroll"><table><thead><tr><th>{en?'Resource / reference':'対象 / 外部番号'}</th><th>{tr('状態')}</th><th>{tr('金額')}</th><th>{tr('日時')}</th>{onOpen&&<th/>}</tr></thead><tbody>{result.data.map((r:Row)=><tr key={r.id}><td><strong>{r.data?.description??r.data?.name??r.data?.title??r.data?.subject??r.data?.type??r.business_key??r.id}</strong><small>{r.business_key??r.id}</small></td><td><Badge>{r.status}</Badge></td><td><Amount value={r.amount}/></td><td>{new Date(r.created_at).toLocaleString(en?'en-GB':'ja-JP',{timeZone:localStorage.getItem('exw-timezone')??'Asia/Tokyo'})}</td>{onOpen&&<td><button className="secondary compact" onClick={()=>onOpen(r)}>{tr('詳細')}</button></td>}</tr>)}</tbody></table></div>:<Empty/>}
 <div className="pagination"><button className="secondary compact" disabled={busy||cursors.length<=1} onClick={()=>{const next=cursors.slice(0,-1);setCursors(next);void load(next.at(-1));}}>{tr('前へ')}</button><span>{en?'Page':'ページ'} {cursors.length} · {result.data.length}/25</span><button className="secondary compact" disabled={busy||!result.next_cursor} onClick={()=>{setCursors([...cursors,result.next_cursor]);void load(result.next_cursor);}}>{tr('次へ')}</button></div></div>;
}
export function ShareLink({url}:{url:string}){const [image,setImage]=useState(''),[error,setError]=useState('');const lang=useLanguage();return <div><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(url);setError(lang==='en'?'Link copied.':'リンクをコピーしました。');}catch{setError(url);}}}>{tr('コピー')}</button><button className="text-button" onClick={async()=>{try{if(image){setImage('');return;}const qr=await import('qrcode');setImage(await qr.toDataURL(url,{width:220,margin:4,errorCorrectionLevel:'M'}));}catch{setError(lang==='en'?'Could not generate QR. Use the link.':'QRを生成できませんでした。リンクを利用してください。');}}}>QR</button>{image&&<div><img src={image} width={220} height={220} alt={lang==='en'?'QR code for sharing this payment link':'この支払リンクを共有するQRコード'}/><small>{lang==='en'?'Sign in to the same demo workspace to open this link.':'同じデモ環境のログインが必要です。'}</small><a href={url}>{tr('リンク')}</a></div>}{error&&<small role="status">{error}</small>}</div>;}
