'use client';
import {tr,useLanguage,setLanguage} from '../../../packages/ui/src/i18n';
import {useState,useEffect} from 'react';
import {Code2,Plus,ExternalLink,Copy,Play,ShieldCheck,CheckCircle2,AlertCircle,RefreshCw,Clock,RotateCcw,ArrowUpRight} from 'lucide-react';
import {Badge,Amount,Empty} from '../../../packages/ui/src/index';
import type {Action} from './portal';
import {RecordBrowser,downloadCsv} from './records';
import {Investigation,DemoSnapshots} from './investigation';
import {ConcurrencyLab,ConcurrentApprovals} from './concurrency-lab';
type Row=Record<string,any>;type Props={data:Row;request:any;act:(a:Action)=>void;simple:any;showSecret?:any;section?:string;apiRecords?:any;reset?:()=>void};
const API=process.env.NEXT_PUBLIC_EXW_API_URL??'http://localhost:4000';
const reason={key:'reason',label:tr("理由（監査ログに記録）"),value:tr("デモ上の確認・検証")};
const capabilityNames={can_pay:tr("新規支払い"),can_receive:tr("入金受取"),can_payout:tr("出金"),can_refund:tr("返金実行"),can_capture:tr("既存オーソリ確定")};
export function Developer({data,request,act,simple}:Props){const [tab,setTab]=useState('overview'),[apiPath,setApiPath]=useState('/v1/orders'),[method,setMethod]=useState('GET'),[body,setBody]=useState(tr("{\n  \"merchant_order_id\": \"PLAYGROUND-001\",\n  \"amount\": {\"currency\":\"JPY\",\"value\":\"1000\"},\n  \"items\": [{\"name\":\"デモ商品\",\"quantity\":1,\"unit_amount\":{\"currency\":\"JPY\",\"value\":\"1000\"}}]\n}")),[response,setResponse]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
return <><div className="tabs">{[['overview',tr("APIガイド")],['applications',tr("アプリ・秘密鍵")],['webhooks','Webhook'],['playground','Playground'],['logs',tr("APIログ")]].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
{tab==='overview'&&<><div className="developer-hero"><div><Badge>BUILD WITH ExPress</Badge><h2>{tr("数行からはじめる、")}<br/>{tr("オンライン決済。")}</h2><p>{tr("注文をつくり、承認を受け取り、売上を確定する。")}<br/>{tr("ホスト型チェックアウトとSDKで、ひとつの流れに。")}</p><a href={API+'/docs'} target="_blank" rel="noreferrer" className="primary">{tr("対話型APIドキュメント ")}<ExternalLink size={16}/></a></div><Code2 size={140}/></div><div className="two-grid"><section className="card"><h2>{tr("サーバーSDK")}</h2><pre>{`import { ExPressClient } from '@exw/sdk-server';

const exw = new ExPressClient({
  baseUrl: '${API}',
  clientId: process.env.EXW_CLIENT_ID,
  clientSecret: process.env.EXW_CLIENT_SECRET
});

const order = await exw.createOrder({
  merchant_order_id: 'SHOP-001',
  amount: { currency: 'JPY', value: '1000' },
  items: [{ name: 'Sample', quantity: 1,
    unit_amount: { currency: 'JPY', value: '1000' } }]
}, 'order-SHOP-001');`}</pre></section><section className="card"><h2>{tr("決済連携の流れ")}</h2><ol className="steps"><li><strong>{tr("サーバーで注文を作成")}</strong><p>{tr("価格と数量を検証し、同じ冪等キーで再試行。")}</p></li><li><strong>{tr("ExPressで支払いを承認")}</strong><p>{tr("ブラウザSDKがホスト型チェックアウトに遷移。")}</p></li><li><strong>{tr("サーバーで照会・売上確定")}</strong><p>{tr("金額・通貨・加盟店・注文の対応を検証。")}</p></li><li><strong>{tr("Webhookを検証")}</strong><p>{tr("署名・時刻・event IDを検証して重複排除。")}</p></li></ol><p className="muted">{tr("SDKとコールバックは決済確定の証拠にはしません。Webリクエストとは独立したワーカーが通知を配信します。")}</p></section></div></>}
{tab==='applications'&&<><div className="toolbar"><button className="primary" onClick={()=>act({title:tr("アプリ登録"),description:tr("client secretはこの時だけ表示します。ブラウザへ保存せず、ECサーバーで利用してください。"),path:'/v1/merchant/applications',fields:[{key:'name',label:tr("アプリ名"),value:'My demo application'},{key:'scopes',label:'Scopes (comma separated)',value:(data.scopes??[]).join(',')}],body:v=>({name:v.name,scopes:v.scopes.split(',').map((s:string)=>s.trim()).filter(Boolean)})})}><Plus size={16}/>{tr("アプリを登録")}</button></div><section className="card">{(data.credentials??[]).map((c:Row)=><article className="credential" key={c.id}><div><h3>{c.data.name} <Badge>{c.status}</Badge></h3><code>client_id: {c.data.client_id}</code><p className="muted">{c.data.scopes?.join(' · ')}</p></div><div className="toolbar"><button className="secondary" onClick={()=>simple(tr("秘密鍵を更新"),`/v1/merchant/applications/${c.id}/rotate`,tr("既存のアクセストークンも失効します。ECサーバーの資格情報を更新してください。"))}>{tr("更新")}</button><button className="text-button danger" onClick={()=>simple(tr("秘密鍵を失効"),`/v1/merchant/applications/${c.id}/revoke`)}>{tr("失効")}</button></div></article>)}</section><section className="card"><h2>{tr("許可return URL / cancel URL")}</h2><pre>{JSON.stringify({return_urls:data.merchant?.data.return_urls,cancel_urls:data.merchant?.data.cancel_urls},null,2)}</pre><button className="secondary" onClick={()=>act({title:tr("戻り先URLを登録"),description:tr("完全一致で検証します。HTTPS URLまたはローカルのサンプルECのみ。"),path:'/v1/merchant/return-urls',method:'PATCH',fields:[{key:'return_url',label:'return URL',value:data.merchant?.data.return_urls?.[0]},{key:'cancel_url',label:'cancel URL',value:data.merchant?.data.cancel_urls?.[0]}],body:v=>({return_urls:[v.return_url],cancel_urls:[v.cancel_url]})})}>{tr("戻り先URLの設定")}</button></section></>}
{tab==='webhooks'&&<><div className="toolbar"><button className="primary" onClick={()=>act({title:tr("Webhookを登録"),description:tr("管理者が許可した通知先だけを登録できます。"),path:'/v1/webhook-endpoints',fields:[{key:'url',label:tr("通知URL"),value:(process.env.NEXT_PUBLIC_EXW_STORE_URL??'http://localhost:3001')+'/webhooks/express-wallet'}],body:v=>({url:v.url,events:['capture.succeeded','refund.succeeded','authorization.created']})})}><Plus size={16}/>{tr("通知先を登録")}</button></div><section className="card">{(data.webhook_endpoints??[]).map((e:Row)=><article className="credential" key={e.id}><div><code>{e.data.url}</code><p><Badge>{e.status}</Badge> {e.data.events.join(' / ')}</p></div><div className="toolbar"><button className="secondary" onClick={()=>act({title:tr('Webhookを登録'),description:tr('管理者が許可した通知先だけを登録できます。'),path:'/v1/webhook-endpoints/'+e.id,method:'PATCH',fields:[{key:'url',label:tr('通知URL'),value:e.data.url},{key:'events',label:'Events (comma separated)',value:e.data.events.join(',')}],body:v=>({url:v.url,events:v.events.split(',').map((s:string)=>s.trim()).filter(Boolean)})})}>{tr('編集')}</button><button className="secondary" onClick={()=>simple(tr("テスト通知を送信"),`/v1/webhook-endpoints/${e.id}/test`)}>{tr("テスト")}</button><button className="secondary" onClick={()=>simple(tr("署名鍵を更新"),`/v1/webhook-endpoints/${e.id}/rotate-secret`,tr("新しい鍵を受信側へ設定してください。旧鍵は24時間の移行期間を設けます。"))}>{tr("鍵更新")}</button><button className="text-button" onClick={()=>act({title:tr("通知先を停止"),description:tr("この通知先への配信を停止します。"),method:'DELETE',path:'/v1/webhook-endpoints/'+e.id,body:()=>undefined})}>{tr("停止")}</button></div></article>)}</section><section className="card"><h2>{tr("署名検証の例")}</h2><p className="muted">{tr("raw bodyとExPress-Signatureヘッダーをそのまま渡します。鍵更新中は新旧の鍵を配列で渡し、event IDで重複を排除してから最新状態をAPIで照会します。")}</p><pre>{`import { verifyWebhook } from '@exw/sdk-server';
// ExPress-Signature: t=UNIX_SECONDS,v1=HMAC_SHA256(secret, timestamp + "." + raw_body)
app.post('/webhooks/express-wallet', async (req, res) => {
  const ok = verifyWebhook(rawBody, req.headers['express-signature'], [currentSecret, previousSecret]);
  if (!ok) return res.status(401).end();
  // 1. dedupe by event_id  2. re-read GET /v1/orders/{id}  3. never move state backwards
});`}</pre></section><section className="card"><h2>{tr("配信履歴")}</h2><div className="table-scroll"><table><thead><tr><th>{tr("イベント / delivery")}</th><th>{tr("試行")}</th><th>HTTP</th><th>{tr("状態")}</th><th></th></tr></thead><tbody>{(data.webhook_deliveries??[]).map((d:Row)=><tr key={d.id}><td><code>{d.data.event_id}</code><small>{d.id}</small></td><td>{d.data.attempt}</td><td>{d.data.http_status??'—'}</td><td><Badge>{d.status}</Badge></td><td><button className="secondary compact" onClick={()=>simple(tr("通知を再配信"),`/v1/webhook-deliveries/${d.id}/retry`,tr("同一event IDを新しい署名時刻・delivery IDで再送します。"))}>{tr("再送")}</button></td></tr>)}</tbody></table></div>{!data.webhook_deliveries?.length&&<Empty/>}</section></>}
{tab==='playground'&&<section className="card"><h2>API Playground</h2><p>{tr("選択したExPress APIへ実リクエストを送信します。POSTは注文を作成します。")}</p><div className="playground"><div><div className="toolbar"><select aria-label="HTTP method" value={method} onChange={e=>setMethod(e.target.value)}><option>GET</option><option>POST</option></select><select aria-label="API path" value={apiPath} onChange={e=>setApiPath(e.target.value)}><option>/v1/orders</option><option>/v1/balances</option><option>/v1/webhook-deliveries</option></select></div><textarea aria-label="Request JSON" className="code-input" value={body} onChange={e=>setBody(e.target.value)} rows={13}/><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await request('/v1/merchant/playground','POST',{method,path:apiPath,body:method==='POST'?JSON.parse(body):undefined,idempotency_key:crypto.randomUUID()});setResponse(result);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><Play size={15}/>{tr("実行")}</button>{error&&<p className="error">{error}</p>}</div><div><h3>Response</h3>{response?<><div className="toolbar"><Badge>{response.status}</Badge><span>{response.latency_ms} ms</span><code>{response.request_id}</code></div><pre>{JSON.stringify(response.response,null,2)}</pre><h3>curl (POSIX sh / bash)</h3><p className="muted">{tr("EXW_ACCESS_TOKEN には POST /v1/oauth/token で取得したアクセストークンを設定します。秘密鍵とトークンは表示例に埋め込みません。")}</p><pre>{response.curl}</pre><h3>curl.exe (Windows PowerShell)</h3><pre>{response.curl_powershell}</pre></>:<Empty>{tr("リクエストを実行すると結果を表示します。")}</Empty>}</div></div></section>}
{['logs','webhooks'].includes(tab)&&<section className="card"><h2>{tr('検索')}</h2><RecordBrowser request={request} endpoint={tab==='logs'?'/v1/merchant/records/api_logs':'/v1/webhook-deliveries'}/></section>}
{tab==='logs'&&<section className="card"><h2>{tr("APIリクエストログ")}</h2><div className="table-scroll"><table><thead><tr><th>Request ID</th><th>Method / Path</th><th>{tr("結果")}</th><th>{tr("時間")}</th></tr></thead><tbody>{(data.api_logs??[]).map((r:Row)=><tr key={r.id}><td><code>{r.data.request_id}</code></td><td>{r.data.method} <code>{r.data.path}</code></td><td>{r.data.status}</td><td>{r.data.latency_ms} ms</td></tr>)}</tbody></table></div></section>}
</>;}
export function Admin({section,data,request,act,simple,apiRecords}:Props){const [q,setQ]=useState(''),[table,setTable]=useState('orders'),[results,setResults]=useState<Row|null>(null),[error,setError]=useState('');const review=(a:Row,type:string)=>act({title:tr("模擬審査・能力別制限"),description:tr("理由と変更内容を監査ログへ記録します。閲覧と返金受取は可能です。"),path:'/v1/admin/accounts/'+a.id+'/review',fields:[{key:'review',label:tr("模擬審査状態"),value:a.data.kyc??a.data.review,options:[{value:'pending',label:tr("確認中")},{value:type==='user'?'verified':'approved',label:tr("確認済み・承認")},{value:'correction_required',label:tr("要修正")}]},...Object.entries(capabilityNames).map(([k,label])=>({key:k,label,type:'checkbox',value:a.data.capabilities?.[k]!==false})),reason],body:v=>({type,review:v.review,reason:v.reason,capabilities:Object.fromEntries(Object.keys(capabilityNames).map(k=>[k,!!v[k]]))})});
return <>{section==='overview'&&<><div className="stats-grid">{[['orders',tr("決済注文")],['provider_attempts',tr("結果不明")],['webhook_deliveries',tr("通知失敗")],['risk_reviews',tr("手動審査")]].map(([key,label])=><div className="card stat" key={key}><p>{label}</p><strong className="stat-number">{data.counts?.[key]??'—'}</strong><small>{tr("現在のサンプル環境")}</small></div>)}</div><section className="card"><div className="section-heading"><h2>{tr("台帳の整合性")}</h2><Badge tone={data.reconciliation?.ok?'green':'red'}>{data.reconciliation?.ok?tr("検査OK"):tr("要調査")}</Badge></div><p>{tr("仕訳ごとの借貸一致と、全勘定の正本からの残高再計算を検証しています。")}</p><p>{data.reconciliation?.journals.length??0} {tr(" 仕訳 / ")}{data.reconciliation?.accounts.length??0} {tr(" 勘定")}</p></section><section className="card"><h2>{tr("横断検索")}</h2><div className="toolbar"><select aria-label={tr("検索対象")} value={table} onChange={e=>setTable(e.target.value)}>{['orders','users','merchants','authorizations','captures','refunds','payouts','outbox','webhook_deliveries','jobs','audit_logs','journal_entries'].map(t=><option key={t}>{t}</option>)}</select><input aria-label={tr("検索文字列")} value={q} onChange={e=>setQ(e.target.value)} placeholder={tr("ID / 注文番号 / 名前")}/><button className="secondary" onClick={async()=>{try{setResults(await request(table==='journal_entries'?'/v1/admin/journals?'+new URLSearchParams({q}):'/v1/admin/search?'+new URLSearchParams({table,q})));}catch(e:any){setError(e.message);}}}>{tr("検索")}</button></div>{error&&<p className="error">{error}</p>}{results&&apiRecords(results.data,table==='journal_entries'?['id','business_event','description','reference_id','amount']:['id','status','amount','data'])}</section></>}
{section==='accounts'&&<>{[['users',tr("利用者"),'user'],['merchants',tr("加盟店"),'merchant']].map(([key,label,type])=><section className="card" key={key}><h2>{label}</h2><div className="table-scroll"><table><thead><tr><th>{tr("名前")}</th><th>{tr("審査")}</th><th>{tr("制限")}</th><th></th></tr></thead><tbody>{(data[key]??[]).map((u:Row)=><tr key={u.id}><td><strong>{u.data.name}</strong><small>{u.id}</small></td><td><Badge>{u.data.kyc??u.data.review??'—'}</Badge></td><td>{Object.entries(u.data.capabilities??{}).filter(([_,v])=>!v).map(([k])=>capabilityNames[k as keyof typeof capabilityNames]).join(' / ')||tr("制限なし")}</td><td><button className="secondary compact" onClick={()=>review(u,type)}>{tr("審査・制限")}</button></td></tr>)}</tbody></table></div></section>)}</>}
{section==='ledger'&&<><Investigation request={request} act={act} journals={data.reconciliation?.journals??[]}/><section className="card"><div className="section-heading"><h2>{tr("残高再計算")}</h2><Badge tone={data.reconciliation?.ok?'green':'red'}>{data.reconciliation?.ok?tr("借貸・残高一致"):tr("不一致を検出")}</Badge></div>{apiRecords(data.reconciliation?.accounts??[],['owner_id','kind','balance','recalculated'])}</section><section className="card"><h2>{tr("仕訳と業務イベント")}</h2>{apiRecords(data.reconciliation?.journals??[],['id','business_event','description','difference'])}<h3>{tr("業務レコードとの照合")}</h3>{apiRecords(data.reconciliation?.business??[],['resource_id','rule','expected','actual','ok'])}</section><section className="card"><h2>{tr("残高訂正")}</h2><p>{tr("直接編集は行いません。理由と模擬外部資金の対向勘定を伴う調整仕訳を記録します。")}</p><button className="secondary" onClick={()=>act({title:tr("調整仕訳の記録"),description:tr("模擬外部資金を対向勘定として、指定した利用可能残高を訂正します。"),path:'/v1/admin/adjustments',financial:true,fields:[{key:'owner_id',label:tr("対象ID")},{key:'type',label:tr("対象区分"),options:[{value:'user',label:tr("利用者")},{value:'merchant',label:tr("加盟店")}]},{key:'direction',label:tr("訂正方向"),options:[{value:'credit',label:tr("増加")},{value:'debit',label:tr("減少")}]},{key:'amount',label:tr("金額（円）"),value:'1000',type:'number'},reason],body:v=>({...v,amount:{currency:'JPY',value:v.amount},counter_account:'mock_external'})})}>{tr("調整仕訳を作成")}</button></section></>}
{section==='risk'&&<section className="card"><h2>{tr("手動審査キュー")}</h2>{(data.risk_reviews??[]).map((r:Row)=><article className="credential" key={r.id}><div><h3>{r.data.reason}</h3><code>{r.data.rule} / {r.data.rule_version}</code><p>{r.parent_id}</p><Badge>{r.status}</Badge></div><button className="secondary" disabled={r.status==='resolved'} onClick={()=>act({title:tr("審査結果を記録"),description:tr("理由と対象を監査ログへ記録します。"),path:'/v1/admin/risk-reviews/'+r.id+'/resolve',fields:[reason]})}>{tr("審査を記録")}</button></article>)}{!data.risk_reviews?.length&&<Empty/>}</section>}
{section==='jobs'&&['provider_attempts','jobs','webhook_deliveries','outbox'].map(key=><section className="card" key={key}><h2>{key}</h2>{apiRecords(data[key]??[],['id','status','data'])}{key==='jobs'&&(data.jobs??[]).filter((j:Row)=>j.status==='failed').map((j:Row)=><div className="toolbar" key={j.id}><code>{j.id}</code><Badge>{j.status}</Badge><button className="secondary compact" onClick={()=>act({title:tr("失敗ジョブを再試行"),description:tr("理由を監査ログへ記録し、ジョブを再取得可能にします。"),path:'/v1/admin/jobs/'+j.id+'/retry',fields:[reason]})}>{tr("再試行")}</button></div>)}{key==='webhook_deliveries'&&(data.webhook_deliveries??[]).filter((d:Row)=>['failed','dead_letter'].includes(d.status)).map((d:Row)=><div className="toolbar" key={d.id}><code>{d.id}</code><Badge>{d.status}</Badge><button className="secondary compact" onClick={()=>act({title:tr("通知を再配信"),description:tr("同一event IDを新しいdelivery IDで再送し、理由を監査ログへ記録します。"),path:'/v1/admin/webhook-deliveries/'+d.id+'/retry',fields:[reason]})}>{tr("再送")}</button></div>)}</section>)}
{section==='audit'&&<section className="card"><h2>{tr("監査ログ")}</h2>{apiRecords(data.audit_logs??[],['created_at','data'])}</section>}
{section==='settings'&&<section className="card"><h2>{tr("デモの決済設定")}</h2><pre>{JSON.stringify(data.settings,null,2)}</pre><button className="primary" onClick={()=>act({title:tr("決済設定を変更"),description:tr("変更後の取引から適用します。確定済み手数料のsnapshotは変わりません。"),path:'/v1/admin/settings',method:'PATCH',fields:[{key:'fee_bps',label:tr("料率（basis point）"),value:data.settings?.fee_bps??'300'},{key:'fee_fixed',label:tr("固定手数料（円）"),value:data.settings?.fee_fixed??'30'},{key:'limit',label:tr("取引上限（円）"),value:data.settings?.limit??'10000000'},{key:'subscription_limit',label:tr("月額課金上限（円）"),value:data.settings?.subscription_limit??'100000'},{key:'settlement_seconds',label:tr("精算待機時間（秒）"),value:data.settings?.settlement_seconds??'60'},reason]})}>{tr("設定を変更")}</button></section>}
</>;}
export function Demo({data,request,act,simple,reset}:Props){const [tab,setTab]=useState('scenarios');const scenarios=[[tr("残高支払い → 即時確定"),tr("ウォレット → サンプルEC → 即時売上確定で購入。承認して店舗に戻り、支払済みと発送1件を確認。")],[tr("模擬カード支払い → 元カード返金"),tr("チェックアウトで模擬Visaを選択。購入履歴で部分返金。ウォレット残高が変わらないことを確認。")],[tr("残高不足 → チャージ → 再承認"),tr("残高を超える注文を承認。チャージ後、同じチェックアウトで再承認。")],[tr("承認後にブラウザ離脱 → 照会復旧"),tr("承認後にタブを閉じ、ECの購入履歴から「ExPressに照会して更新」。")],[tr("未確定オーソリの期限切れ"),tr("出荷時確定で承認。業務時計を25時間進め、ワーカー実行後に保留0円を確認。")],[tr("部分確定 → 残額解放 → 部分返金"),tr("商品2個購入。一部出荷で金額を確定し、最終確定を選択。そのcaptureに部分返金。")],[tr("captureの100並列・重複"),tr("加盟店へ切り替え、下の100並列パネルで同じキーを選択して実行。captureが1件であることを確認。")],[tr("同一残高の同時支払い"),tr("下の同時承認パネルで2つのチェックアウトを確認・承認します。10,000円に対する8,000円2件は自動テストでも検証します。")],[tr("providerタイムアウト後成功"),tr("処理を作成し、下の対象operationにtimeout_successを設定。照会ジョブで成功へ収束。")],[tr("Webhook 500 → 自動再送"),tr("ECの購入履歴で次のWebhookを500に設定。決済後、配信履歴で失敗と再送成功を確認。")],[tr("重複・順序逆転"),tr("開発者ポータルから古い通知を再送。ECは最新照会へ収束し発送件数は増えない。")],[tr("加盟店出金失敗 → 保留解放"),tr("ワーカーを停止して出金を申請。対象provider attemptをdeclineにしてワーカー再開。")],[tr("出金後の返金原資不足 → 入金"),tr("精算後に加盟店残高を出金。全額返金で不足を確認し、加盟店追加入金後に再試行。")],[tr("定期課金失敗 → 再試行 / 撤回"),tr("加盟店でプラン・購読を作り利用者が同意。残高不足後に入金し時計を1日進める。")],[tr("新規支払い制限・返金受取"),tr("運営者でcan_payだけを解除。新規支払い拒否、過去明細閲覧と返金受取を確認。")],[tr("他加盟店・workspaceへのアクセス拒否"),tr("別人物と別デモのIDをAPIで照会。pnpm test の認可テストで403/404を確認。")]];
return <><div className="demo-controls"><div><FlaskConicalIcon/><h2>{tr("障害も、回復も、見えるように。")}</h2><p>{tr("対象は現在の隔離環境だけです。外部金融機関との境界を模擬し、内部処理は実際のAPI・台帳を通します。")}</p></div><div className="button-stack"><button className="secondary" onClick={()=>simple(tr("ジョブ取得を一時停止"),'/v1/demo/worker',tr("新しいジョブ取得を止めます。すでに送信した操作は完了する場合があります。"),false,{paused:true})}>{tr("ジョブ取得を一時停止")}</button><button className="secondary" onClick={()=>simple(tr("ジョブ取得を再開"),'/v1/demo/worker',tr("現在のデモの処理を再開します。"),false,{paused:false})}>{tr("ジョブ取得を再開")}</button><button className="secondary" onClick={()=>act({title:tr("業務時計を進める"),description:tr("現在のworkspaceだけに適用します。システム時計やWebhook署名時刻は変更しません。"),path:'/v1/demo/clock',fields:[{key:'seconds',label:tr("進める秒数"),value:'90000',type:'number'}],body:v=>({seconds:Number(v.seconds)})})}><Clock size={16}/>{tr("業務時計を進める")}</button><button className="secondary danger" onClick={reset}><RotateCcw size={16}/>{tr("このデモをリセット")}</button></div></div><div className="stats-grid">{Object.entries(data.balances??{}).filter(([k])=>k!=='currency').slice(0,4).map(([k,v])=><div className="stat card" key={k}><p>{k}</p><Amount value={String(v)} className="stat-number"/></div>)}</div><div className="tabs">{[['scenarios',tr("16のシナリオ")],['provider',tr("模擬プロバイダー")],['timeline',tr("イベント・台帳")],['api',tr("APIログ")]].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
{tab==='scenarios'&&<div className="scenario-grid">{scenarios.map(([title,description],i)=><section className="card scenario" key={title}><span className="scenario-number">{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{description}</p></section>)}</div>}
{tab==='scenarios'&&<DemoSnapshots request={request} scope={data.workspace_id+':'+data.generation}/>}
{tab==='scenarios'&&data.role==='consumer'&&<ConcurrentApprovals request={request}/>}
{tab==='scenarios'&&data.role!=='consumer'&&<ConcurrencyLab request={request} authorizations={data.authorizations??[]}/>}
{tab==='provider'&&<section className="card"><h2>{tr("operationに紐づく模擬結果")}</h2><p>{tr("高速で完了する処理に失敗を注入する場合は、ワーカーを停止した状態で申請してから設定します。完了済みの結果は変更できません。")}</p>{(data.provider_attempts??[]).map((a:Row)=><article className="credential" key={a.id}><div><h3>{a.data.kind} <Badge>{a.status}</Badge> <Amount value={a.amount}/></h3><code>{a.id}</code><small>operation: {a.parent_id}</small></div><button className="secondary" disabled={['succeeded','failed'].includes(a.status)} onClick={()=>act({title:tr("模擬結果を設定"),description:tr("このoperationだけに適用します。"),path:'/v1/demo/scenarios',fields:[{key:'mode',label:tr("模擬動作"),options:[{value:'timeout_success',label:tr("タイムアウト後成功")},{value:'decline',label:tr("拒否・失敗")},{value:'pending',label:tr("処理中を維持")},{value:'success',label:tr("成功")},{value:'crash_after_success',label:tr("成功後・結果保存前の停止")}]}],body:v=>({attempt_id:a.id,mode:v.mode})})}>{tr("結果を設定")}</button></article>)}{!data.provider_attempts?.length&&<Empty>{tr("チャージ・模擬カード決済・出金を申請すると表示されます。")}</Empty>}</section>}
{tab==='timeline'&&<div className="two-grid"><section className="card"><h2>{tr("業務イベント → Webhook")}</h2>{(data.outbox??[]).map((e:Row)=><div className="timeline-item" key={e.id}><span className="live-dot"/><div><strong>{e.data.type}</strong><small>{e.data.resource_id} · version {e.data.resource_version}</small><Badge>{e.status}</Badge></div></div>)}</section><section className="card"><h2>{tr("台帳検証 ")}<Badge tone={data.reconciliation?.ok?'green':'red'}>{data.reconciliation?.ok?tr("一致"):tr("要調査")}</Badge></h2><pre>{JSON.stringify(data.reconciliation,null,2)}</pre></section></div>}
{tab==='api'&&<section className="card"><h2>{tr("APIリクエスト")}</h2><pre>{JSON.stringify((data.api_logs??[]).map((r:Row)=>r.data),null,2)}</pre></section>}
</>;}
function FlaskConicalIcon(){return <span className="demo-flask"><Code2 size={25}/></span>;}
export function DailyReports({request}:{request:any}){const [report,setReport]=useState<Row|null>(null),[error,setError]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');async function load(){try{setReport(await request('/v1/merchant/reports?'+new URLSearchParams({...from?{from:new Date(from).toISOString()}:{},...to?{to:to+'T23:59:59.999Z'}:{}})));setError('');}catch(e:any){setError(e.message);}}useEffect(()=>{void load();},[request]);return <section className="card"><div className="section-heading"><h2>{tr("日次売上・返金・手数料 ")}<small>UTC / JPY</small></h2></div><div className="toolbar"><input aria-label={tr("売上集計開始日")} type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label={tr("売上集計終了日")} type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="secondary compact" onClick={load}>{tr("期間を適用")}</button><button className="secondary compact" disabled={!report?.data.length} onClick={()=>downloadCsv(report!.data,'express-wallet-daily.csv')}>CSV</button></div>{error&&<p className="error">{error}</p>}{report?.data.length?<div className="table-scroll"><table><thead><tr><th>{tr("日付")}</th><th>{tr("件数")}</th><th>{tr("確定額")}</th><th>{tr("返金額")}</th><th>{tr("手数料")}</th></tr></thead><tbody>{report.data.map((r:Row)=><tr key={r.day}><td>{r.day}</td><td>{r.count}</td><td><Amount value={r.captured}/></td><td><Amount value={r.refunded}/></td><td><Amount value={r.fees}/></td></tr>)}</tbody></table></div>:<Empty>{tr("指定期間の売上はありません。")}</Empty>}</section>;}
